### ISSUE TITLE
Look into DeprecationWarning for usage of np.fromstring

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#103]
/home/snowal/scripts/rioxarray/rioxarray/_io.py:229: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
    new_val = np.fromstring(value.strip("{}"), dtype="float", sep=",")

**Comment by agrouaze** [comment]
Hi @snowman2 ,
I think this old issue should be re-opened because, the `try-except` added don't prevent from raising failure in `pytest`.
