### ISSUE TITLE
to_raster doesn't set nodata value acconding to passed dtype

### ISSUE THREAD

**Issue by arkanoid87** [corteva/rioxarray#113]
```
$ conda list | grep rioxarray
rioxarray                 0.0.26                     py_0    conda-forge
```
If you pick an unsigned dtype, rioxarray sets nodata to -1 but the pixel will contain 255
```
mygrid.rio.to_raster("mygrid.tif", compress='LZW', tiled=True, dtype="int8")
with rasterio.open("mygrid.tif", mode='r+') as src:
    print(src.nodata) # prints -1
    src.data = 255 # fix issue for int8
```

issue doesn't seem to exist when using floating point dtypes, but I've just tested with int8 and float32

**Comment by snowman2** [comment]
@arkanoid87, thanks for the report. To help with debugging, mind adding:

1. Output of `python -c "import rioxarray; rioxarray.show_versions()"`
2. An example file to test with?

**Comment by snowman2** [comment]
Also, what is contained in:
```
mygrid.rio.nodata
mygrid.rio.encoded_nodata
```
And what was the original dtype?

**Comment by arkanoid87** [comment]
I don't have a quick and dirty minimal example file to paste now (I'll try to create that soon), but I can fill the other points

>     1. python -c "import rioxarray; rioxarray.show_versions()"

```
$ python -c "import rioxarray; rioxarray.show_versions()"
proj_create: Open of /opt/conda/share/proj failed
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
rioxarray (0.0.26) deps:
  rasterio: 1.0.28
    xarray: 0.14.1
      GDAL: 2.4.4

Other python deps:
    pillow: 7.1.2
     scipy: 1.2.1
    pyproj: 2.5.0

System:
    python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)  [GCC 7.3.0]
executable: /opt/conda/bin/python
   machine: Linux-4.15.0-96-generic-x86_64-with-debian-buster-sid
```

> mygrid.rio.nodata
> mygrid.rio.encoded_nodata
```
>>> print(mygrid.dtype, mygrid.rio.nodata, mygrid.rio.encoded_nodata)
float64 -1 None
```

I immediatly see that the source dtype if float64 and that's a bug in my procedure, but I think that nodata and dtype passed to to_raster function talk each other

**Comment by snowman2** [comment]
By default, `rioxarray` uses the `nodata` value in the raster when creating a new raster. If you have a different nodata value, I would recommend using [write_nodata](https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray.rioxarray.RasterArray.write_nodata) before `to_raster` if you have a different nodata value:

```python
mygrid.rio.write_nodata(255, inplace=True)
```

**Comment by arkanoid87** [comment]
> By default, `rioxarray` uses the `nodata` value in the raster when creating a new raster. If you have a different nodata value, I would recommend using [write_nodata](https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray.rioxarray.RasterArray.write_nodata) before `to_raster` if you have a different nodata value:
> 
> ```python
> mygrid.rio.write_nodata(255, inplace=True)
> ```

I think that I shouldn't have to select nodata value manually. I start from a dataarray with nan values and float64 dtype and I ask rioxarray to save it as raster with dtype int8.

In my opinion selecting automatically nodata value -1 for an unsigned type is wrong. If library can't pick valid nodata value should ask the user to replace nans in dataarray before running to_raster, or ask user to pass it as argument, or just raise error. My 2 cents

**Comment by snowman2** [comment]
> In my opinion selecting automatically nodata value -1 for an unsigned type is wrong.

I agree that the `nodata` value should match the datatype. However, for `int8` `-1` is a valid type:

```python
>>> import numpy
>>> numpy.dtype("int8")
dtype('int8')
>>> numpy.dtype("int8").type(-1)
-1
```
If you want unsigned I would recommend using `uint8`:
```python
>>> numpy.dtype("uint8").type(-1)
255
```

If you do:
```python
mygrid.rio.to_raster("mygrid.tif", compress='LZW', tiled=True, dtype="uint8")
```
You should get the error:
```python
ValueError: Given nodata value, -1.0, is beyond the valid range of its data type, uint8.
```

**Comment by snowman2** [comment]
I am wondering if what you are experiencing is related to: https://github.com/mapbox/rasterio/issues/1878

Can you confirm what your data values are in the raster?

I am thinking that you will have better success if you upgrade to the latest version of `rasterio`.

**Comment by snowman2** [comment]
Just tried with the latest `rasterio` and the data is saved properly. The values have `-1` in the raster, the nodata is `-1`, and the raster dtype was `int8`.
```
rioxarray (0.0.26) deps:
  rasterio: 1.1.4
    xarray: 0.15.1
      GDAL: 2.4.4

Other python deps:
    pillow: 7.1.2
     scipy: 1.4.1
    pyproj: 2.6.1.post1

System:
    python: 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52)  [GCC 7.3.0]
executable: ~/miniconda/envs/rioxarray/bin/python
   machine: Linux-4.15.0-99-generic-x86_64-with-glibc2.10
```
