### ISSUE TITLE
Using defined coordinates as basis for clipping geometry

### ISSUE THREAD

**Issue by nathane1** [corteva/rioxarray#114]
Hi, I'm trying to clip a dataset with rioxarray based on a certain geometry of longitude and latitude values. However, for the data variable I'm using, latitude and longitude are defined in terms of x and y. Ranges for these variables are shown below:

y (y) float64 0.0 4e+03 ... 1.86e+06 1.864e+06
x (x) float64 0.0 4e+03 ... 2.5e+06 2.504e+06
Longitude (y, x) float64 -106.9 -106.9 ... -74.4 -74.34
Latitude (y, x) float64 35.63 35.63 35.64 ... 50.82 50.81

The geometry I have currently defined (intended to be in terms of longitude and latitude) is below: 

geometries = ''' {"type": "Polygon",
        "coordinates": [
        [[-84.0175,37.6929],
            [-85.2345,35.0745],
            [-91.5808,36.62064],
            [-96.3968,37.36303],
            [-98.9204,37.59547],
            [-98.9204,46.82747],
            [-78.6279,46.82747],
            [-80.2795,44.49409],
            [-82.2529,41.13271],
            [-84.0175,37.6929]
        ]]
    }''' 

When I run this, I receive the error 'No data found in bounds. Data variable: APCP_surface'. 

Any tips for how to rework the geometry to have it be in terms of latitude and longitude, or would this even be possible in rioxarray?

Thanks in advance!

**Comment by snowman2** [comment]
Here is the example: https://corteva.github.io/rioxarray/stable/examples/clip_geom.html

I think this should work:
```python
import rioxarray

geometries = [
    {
        "type": "Polygon",
        "coordinates": [
            [
                [-84.0175, 37.6929],
                [-85.2345, 35.0745],
                [-91.5808, 36.62064],
                [-96.3968, 37.36303],
                [-98.9204, 37.59547],
                [-98.9204, 46.82747],
                [-78.6279, 46.82747],
                [-80.2795, 44.49409],
                [-82.2529, 41.13271],
                [-84.0175, 37.6929],
            ]
        ],
    }
]

rds = rioxarray.open_rasterio("dataset.nc")
clipped = rds.rio.clip(geometries, "EPSG:4326")
```

If it doesn't work, do you have a code snippet for something you have tried?

When using this code snippet:
```python
import rioxarray

rds = rioxarray.open_rasterio("dataset.nc")
```
What is the output of:
```python
rds.rio.crs
```

**Comment by nathane1** [comment]
Here is what I've tried with the geometries:

geometries = ' ' ' {"type": "Polygon",
        "coordinates": [
        [[-84.0175,37.6929],
            [-85.2345,35.0745],
            [-91.5808,36.62064],
            [-96.3968,37.36303],
            [-98.9204,37.59547],
            [-98.9204,46.82747],
            [-78.6279,46.82747],
            [-80.2795,44.49409],
            [-82.2529,41.13271],
            [-84.0175,37.6929]
        ]]
    }' ' ' 
cropping_geometries = [gj.loads(geometries)]
hourly_cropped = hourly.rio.clip(geometries = cropping_geometries, crs = 4326)

I am opening this as a dataset, not as a rasterio, because I'm trying to manipulate the data variable contained within the nc file. 

The output I got for hourly.rio.crs (hourly is the name of the dataset I'm using) is CRS.from_epsg(4326)

**Comment by snowman2** [comment]
Hmmm, it seems the CRS that is found is not the CRS of the `x` and `y` columns. `1.86e+06` is out of bounds for geographic coordinates. Do you have a way to determine what the CRS of the x/y columns? What is the CRS when opening with `xarray.open_rasterio`?

**Comment by nathane1** [comment]
There is not a CRS specified when I open the file; I'm using write_crs to set the CRS to 4326. Without it, the .nc doesn't have CRS.

**Comment by Zeitsperre** [comment]
@nathane1 Do you know if the file has a "grid coordinates" definition. Or could you output the results from running `ncdump -h <file>` from the command line? It's unlikely that your CRS is 4326 given the boundaries of it don't surpass longitudes of +180/-180 and latitudes of +90/-90. You might have some luck looking here first: https://gis.stackexchange.com/

**Comment by snowman2** [comment]
What @Zeitsperre mentioned would be the best method. Using the original CRS will enable more accurate clipping.

If you are unable to find the original CRS, I would recommend using the 2D Latitude/Longitude variables to query with the bounds of the geometry:

```python
from shapely.geometry import shape

min_x, min_y, max_x, max_y = shape(gj.loads(geometries)).bounds
hourly_clipped  = hourly.where((hourly.Longitude<=max_x) & (hourly.Longitude>=min_x) & (hourly.Latitude<=max_y) & (hourly.Latitude>=min_y), drop=True)
```

**Comment by nathane1** [comment]
This is the result of running ncdump -h on the file:

(prod) bash-4.4$ ncdump -h HRRRE_0503_00_f01.nc 
netcdf HRRRE_0503_00_f01 {
dimensions:
        y = 467 ;
        x = 627 ;
        time = UNLIMITED ; // (1 currently)
variables:
        double y(y) ;
                y:long_name = "y coordinate of projection" ;
                y:standard_name = "projection_y_coordinate" ;
                y:units = "m" ;
                y:grid_spacing = 4000. ;
        double x(x) ;
                x:long_name = "x coordinate of projection" ;
                x:standard_name = "projection_x_coordinate" ;
                x:units = "m" ;
                x:grid_spacing = 4000. ;
        double latitude(y, x) ;
                latitude:units = "degrees_north" ;
                latitude:long_name = "latitude" ;
        double longitude(y, x) ;
                longitude:units = "degrees_east" ;
                longitude:long_name = "longitude" ;
        double time(time) ;
                time:units = "seconds since 1970-01-01 00:00:00.0 0:00" ;
                time:long_name = "verification time generated by wgrib2 function verftime()" ;
                time:reference_time = 1525305600. ;
                time:reference_time_type = 3 ;
                time:reference_date = "2018.05.03 00:00:00 UTC" ;
                time:reference_time_description = "forecast or accumulated, reference date is fixed" ;
                time:time_step_setting = "auto" ;
                time:time_step = 0. ;
        float APCP_surface(time, y, x) ;
                APCP_surface:_FillValue = 9.999e+20f ;
                APCP_surface:short_name = "APCP_surface" ;
                APCP_surface:long_name = "Total Precipitation" ;
                APCP_surface:level = "surface" ;
                APCP_surface:units = "kg/m^2" ;
                APCP_surface:coordinates = "longitude latitude" ;

// global attributes:
                :Conventions = "CF-1.0" ;
                :History = "created by wgrib2" ;
                :GRIB2_grid_template = 30 ;
}

No CRS is evident to me.

@snowman2 would the method you suggested work in spite of the fact that latitude and longitude are functions of both x and y? If so, I think that might be my best option at this point.

**Comment by snowman2** [comment]
> would the method you suggested work in spite of the fact that latitude and longitude are functions of both x and y?

Yes, that example it is meant for 2D coordinates.

**Comment by nathane1** [comment]
Ok, that method allowed me to successfully clip the dataset. 

Thank you for your help!

**Comment by snowman2** [comment]
Glad to hear it worked :+1:. I am going to close this issue as I believe it has been resolved.

**Comment by melioristic** [comment]
I am stuck with a similar issue. 


`xds = rxr.open_rasterio(
    "data/temp_max/Maxtemp_MaxT_2011.nc",
    masked=True,
)
xds.rio.set_crs(4326)
geodf = gpd.read_file(shp_file)
clipped = xds.rio.clip(geodf.geometry.apply(mapping), "EPSG:4326")
`
I get an error stating : f"No data found in bounds.{_get_data_var_message(self._obj)}"
rioxarray.exceptions.NoDataInBounds: No data found in bounds. Data variable: t

On printing the xds I get the following information. 
oordinates:
  * time         (time) object 2011-01-01 00:00:00 ... 2011-12-31 00:00:00
  * y            (y) float64 37.5 36.5 35.5 34.5 33.5 ... 11.5 10.5 9.5 8.5 7.5
  * x            (x) float64 67.5 68.5 69.5 70.5 71.5 ... 94.5 95.5 96.5 97.5
    spatial_ref  int64 0
Attributes:
    long_name:     DAILYTEMP
    scale_factor:  1.0
    add_offset:    0.0
    grid_mapping:  spatial_ref

Seeking some help. 

The files can be found in the repository https://github.com/melioristic/water-watch And I am trying to run the script io.py in WW folder.

**Comment by snowman2** [comment]
Try changing to use this:
```python
clipped = xds.rio.clip(geodf.geometry.apply(mapping), geodf.crs)
```
