### ISSUE TITLE
Add mask & bbox arguments to open_rasterio

### ISSUE THREAD

**Issue by darribas** [corteva/rioxarray#115]
Is it possible to to use `rioxarray` to read only a section of a file? What I'm thinking would work similarly to [`clip`](https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray.rioxarray.RasterArray.clip) or `clip_box` but would not require a full array in memory.

We do a similar thing in `contextily` to [load only the extent of the local file](https://github.com/geopandas/contextily/blob/master/contextily/plotting.py#L158:L179), and it uses rasterio's masking capabilities.

Would a similar extension of `open_rasterio` be possible and, if so, would it work with COGs so only the read data is transfered over the wire?

Thank you very much in advance for your consideration and for an awesome library!!!

**Comment by snowman2** [comment]
> Is it possible to to use rioxarray to read only a section of a file? 

Actually, by default everything is lazily loaded. It uses the `window` of the data you select to load in.
https://github.com/corteva/rioxarray/blob/6587726a019f46ec68ca94d6cea866abea956a2a/rioxarray/_io.py#L160

So, if you use `rio.clip_box`, it should only load in the data you asked for and behaves exactly like `contextility`. However, it does generate the coordinates for the entire raster, so you do have that overhead.

> Would a similar extension of open_rasterio be possible

It would definitely be useful do do something like that. You could pass in a window when reading in the data from raster and get the transform from the window with `rasterio.windows.transform`. This would reduce the memory and compute overhead when it generated the coordinates.

**Comment by darribas** [comment]
Thanks very much for the quick response!

I'm still getting my head around some of these concepts, so excuse if some of what I say sounds dumb or trivial.

Right now, what I'm envisioning is an extension of the `open_rasterio` where there is an additional argument (`feature` maybe) where you pass a shapely-type/geointerface feature, which could well be a bounding box) and that is used to access only that data in the COG and read it into a `DataArray`:

```python
from shapely.geometry import box
from rioxarray import open_rasterio

subset_box_da = box(minx, miny, maxx, maxy)
da = open_rasterio(cog_url, feature=subset_box_da)
```

On this idea, `open_rasterio` would only read the metadata and the data inside `subset_box_da` from the COG. Do you think this is readily implementable in `rioxarray`? Looking at [how `rio-tiler` efficiently reads](https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/reader.py#L32), I think it'd boil down to reading the metadata, setting up a `window` object and reading it from the file, then use the transform to create the indices _only_ for the window and return it as a `DataArray`. 

Does this sound sensible? If so, I'm happy to play around a bit with implementations separately from this project and share results. If they look OK and you think it'd be good to integrate it, I'd probably need some help to wire it into the current structure of `rioxarray`, as I'm not too familiar with it.

**Comment by snowman2** [comment]
@darribas I like that idea. 

Looks like geopandas has the `mask` &  `bbox` filters on reading in subsets of the data [docs ref](https://geopandas.readthedocs.io/en/latest/io.html#reading-subsets-of-the-data).

It sounds to me like both could be implemented in `rioxarray`:
1. `mask` - [masking-by-shapefile](https://rasterio.readthedocs.io/en/latest/topics/masking-by-shapefile.html)
2. `bbox` - Using [windows.from_bounds](https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.from_bounds) & [windows.transform](https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.transform), this could be achieved.

**Comment by snowman2** [comment]
Here is the function to modify:
https://github.com/corteva/rioxarray/blob/6587726a019f46ec68ca94d6cea866abea956a2a/rioxarray/_io.py#L568

The variable you can use for the handle to the dataset is `riods` (e.g. `riods.clip()` or `riods.read(window=window ...)`)

**Comment by snowman2** [comment]
@darribas do you have any questions or blockers?

**Comment by darribas** [comment]
Haven't had time to put any brainpower on this. With the term ended, I'm hoping to carve out some time this month, will post if anything becomes a blocker, but I think I should be able to have a first stab soon and then have something to show... If anyone else would like to chip in though, by all means :-)

**Comment by snowman2** [comment]
Sounds good - feel free to reach out with questions.

**Comment by darribas** [comment]
Just a quick note I'm a bit out of breath here. I've spent a bit of time but I have to drop this for the time being (semester looming). I will need similar functionality at some point in the near future so might return to it, but for now I can't commit. Apologies. Hopefully I can return at some point. I will also say, I've tried `clip_box` and is very effective as it is on all my tests... Thank you very much in any case for all the support and help.

**Comment by snowman2** [comment]
Sounds good. No worries or rush. It will definitely be nice once it is added.

> I've tried clip_box and is very effective as it is on all my tests

Glad to hear it :+1:. With the latest version of `rioxarray` and `open_rasterio(....parse_coordinates=False)`, I think it should get you pretty close to what you want.

**Comment by snowman2** [comment]
https://github.com/corteva/rioxarray/pull/226

**Comment by alex-translation** [comment]
Relatively new to rioxarray, so I apologize if this is redundant. I'm trying to do exactly what's mentioned here and have implemented a few of the suggestions on this thread. Here's my code:

```
test = rioxarray.open_rasterio(
            filename = cog_url, 
            chunks = 'auto', 
            parse_coordinates = False,
            bounds = bounds,
            masked = True
        )
```

Sadly, it opens the whole file instead of just the bounds I passed in. Can anybody clarify for me what's going on?

Thanks.

**Comment by snowman2** [comment]
I think this is what you are looking for?
```python
test = rioxarray.open_rasterio(
    filename=cog_url, 
    chunks='auto', 
    parse_coordinates=False,
   masked=True
).rio.clip_box(*bounds)
```

**Comment by alex-translation** [comment]
Hi @snowman2, thank you so much. That did the trick perfectly. Can you shed some insight on why this uses so much less memory than the code I had above? Also, is there a way to pass the `bounds` inside of the `open_rasterio()` call itself?

Thanks again,
Alex

**Comment by snowman2** [comment]
> Can you shed some insight on why this uses so much less memory than the code I had above?

The data is lazily loaded. That means that when you call `open_rasterio` the data is not loaded into memory. Using ``rio.clip_box`` directly after loading selects a slice of the data and prevents loading in the entire raster.

> is there a way to pass the bounds inside of the open_rasterio() call itself?

No. See: https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray-open-rasterio
