### ISSUE TITLE
Clip raster band by size

### ISSUE THREAD

**Issue by rfcsilva** [corteva/rioxarray#131]
Currently, rioxarray allows us to clip and image by coordinates and using a polygon. However, in some situations, it may be handy to clip a raster band by size (number of pixels heigh and width). @AMNeves may be able to explain a use case within his geospatial machine learning pipeline.

My suggestion is this new function to work similarly has gdal_translate  -srcwin  xoff yoff xsize ysize. Where you provide the numpy offset index and the number of pixels you want.

```python
import rioxarray
b1 = rioxarray.open_rasterio("myband.tiff")
b1_clipped = b1.clip_size(xoff, yoff, xsize, ysize)
````

Another approach would be to provide the coordinate of a pixel and the radius of pixels that you want.

**Comment by snowman2** [comment]
Have you tried using a rasterio [Window](https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.Window) and `rio.isel_window()`?

**Comment by snowman2** [comment]
You could also just use http://xarray.pydata.org/en/stable/generated/xarray.Dataset.isel.html

**Comment by dshean** [comment]
Yes, I would recommend design/syntax along the lines of rasterio window objects: 
https://rasterio.readthedocs.io/en/latest/topics/windowed-rw.html
https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html

As for radius, you'll still need to extract a square window with dimensions 2*r by 2*r, and then mask or set values to nan.

**Comment by rfcsilva** [comment]
> Have you tried using a rasterio [Window](https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.Window) and `rio.isel_window()`?

Any particular reason to recieve the window as parameter and not building it inside a function? 

> Have you tried using a rasterio [Window](https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.Window) and `rio.isel_window()`?

Yes, that would work. 
I'm just waiting for @AMNeves to say something before I close this Issue.

**Comment by snowman2** [comment]
In #133 I discovered a bug in `rio,isel_window`. I would recommend waiting to use it until the next release.

**Comment by AMNeves** [comment]
This issue came to mind due to how we use raster data in our ML pipeline. Since networks do not care about coordinates (unless you build a network around that ofc), we were wondering if we could cut up rasters via using a set image size. 
E. g. A network wants 265x265x3 image as an input, thus we cut up images with a fixed size, ignoring coordinates we may need later for image reconstruction.

Window seems to suffice in for this case, does it keep coordinate information for the subsets?

**Comment by snowman2** [comment]
> Window seems to suffice in for this case, does it keep coordinate information for the subsets?

Yes, it should keep track of that information.

**Comment by AMNeves** [comment]
> Yes, it should keep track of that information.

@rfcsilva Then I think we can close this issue! Thanks for the answers @snowman2
