### ISSUE TITLE
Make clip_box extend array

### ISSUE THREAD

**Issue by davidbrochart** [corteva/rioxarray#137]
Today `clip_box` has an effect only when the array is shrunk. It would be nice if it could extend the array when the bounding box is bigger than the original one, maybe using xarray's `.pad()`?

**Comment by snowman2** [comment]
This is an interesting idea. Initial questions I have (since I personally haven't needed to do this with a clip before):
1. Is there an equivalent in `rasterio/GDAL`?
2. What is the use case you have where this would be useful?

**Comment by davidbrochart** [comment]
1. I don't think there is an equivalent in rasterio or GDAL. Also, the initial implementation in #138 only uses the simplest padding method of xarray, which is padding with a constant value of NaN, but xarray offers much more: linear ramp, edge value, etc. (see http://xarray.pydata.org/en/stable/generated/xarray.DataArray.pad.html). The API could be different, we could leave `.clip_box()` as it is and have a separate `.pad_box()`, because in the end it's only clipping then padding, but I think it makes sense to have it part of `clip_box`.
2. The next version of [xarray-leaflet](https://github.com/davidbrochart/xarray_leaflet) will depend on rioxarray, and we need this feature to generate the tiles.

**Comment by davidbrochart** [comment]
:+1:
