### ISSUE TITLE
Store transform

### ISSUE THREAD

**Issue by davidbrochart** [corteva/rioxarray#139]
As described [here](https://corteva.github.io/rioxarray/stable/examples/manage_information_loss.html), information can be lost when doing xarray operations. Similar to the `write_crs` method, should we have a `write_transform` method that would ensure the transform gets propagated across operations? It also makes sense because some rioxarray operations, like `clip_box`, could update the transform.

**Comment by snowman2** [comment]
It would be good to have it write according to #129
