### ISSUE TITLE
usage of the rasterio.features module

### ISSUE THREAD

**Issue by Meresmata** [corteva/rioxarray#159]
Hi,

 I am currentenly interessted in the rasterio features module (namely the functions shape and rasterize. Neither did I found it in the documentation, nor could I find it's a undocumented feature.

Did I miss anything? Would implementing this being a larger extent of work?

**Comment by snowman2** [comment]
I think that you are looking for: https://github.com/corteva/geocube

**Comment by Meresmata** [comment]
Hi, yeah. Yes and no. I want to do both raster --> vector and vector --> raster.

**Comment by JessicaS11** [comment]
@Meresmata Did you ever end up building any `raster->vector` functionality? I found this issue while searching for similar functionality, and ended up [creating my own implementation](https://github.com/JessicaS11/icebath/blob/main/icebath/core/build_gdf.py) to build a geodataframe using `rasterio.features.shapes` on an xarray dataset. It's highly application specific (loops through only one variable based on the time dimension) and the code still needs some cleanup, but I wanted to share in case it's helpful. Where the variable data fit into memory it was as simple as adding the transform input to `shapes()`. The trickier part was when the variable data was a dask array that didn't all fit into memory, so a geotransform needed to be constructed per-chunk and then fed into `shapes()` within a `dask.delayed` function call.

**Comment by snowman2** [comment]
Forwarding to geocube: https://github.com/corteva/geocube/issues/65
