### ISSUE TITLE
Incorrect missing value handling when _FillValue is float

### ISSUE THREAD

**Issue by bilelomrani1** [corteva/rioxarray#162]
I am working with [this raster file](https://github.com/corteva/rioxarray/files/5226354/no2_2019_01.tif.zip) which was generated (I believe) with R. 

```python
>>> import rioxarray
>>> raster = rioxarray.open_rasterio('no2_2019_01.tif')
>>> raster.attrs
{'STATISTICS_MAXIMUM': 0.00022005502250977,
 'STATISTICS_MEAN': nan,
 'STATISTICS_MINIMUM': 7.5976657853971e-07,
 'STATISTICS_STDDEV': nan,
 '_FillValue': -3.4e+38,
 'scale_factor': 1.0,
 'add_offset': 0.0,
 'grid_mapping': 'spatial_ref'}
```
The missing values are thus specified with the value `-3.4e+38`. When invoking `.plot()`, the following figure is generated:

```python
>>> raster.plot()
```
![Capture d’écran 2020-09-15 à 18 24 04](https://user-images.githubusercontent.com/16692099/93237635-ad160f00-f780-11ea-8399-57767b262e20.png)

The large negative value is not being ignored when plotting. I ended up manually fixing this issue by masking the array:

```python
>>> import numpy as np
>>> raster = raster.rio.write_nodata(np.float32(raster.rio.nodata))
>>> raster = raster.where(raster != raster.rio.nodata)
>>> raster = raster.rio.write_nodata(np.nan)
>>> raster.plot()
```
![Capture d’écran 2020-09-15 à 18 32 44](https://user-images.githubusercontent.com/16692099/93238539-ddaa7880-f781-11ea-8423-4b07534d548b.png)

I expected the latter figure to be produced without needing to manually change the array nor the attributes of the array. 

#### Environment Information

```python
>>> rioxarray.show_versions()
rioxarray (0.0.31) deps:
  rasterio: 1.1.5
    xarray: 0.16.0
      GDAL: 3.0.4

Other python deps:
     scipy: 1.5.2
    pyproj: 2.6.1.post1

System:
    python: 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:18:42)  [Clang 10.0.1 ]
executable: /Users/bilelomrani/opt/miniconda3/envs/raster/bin/python
   machine: macOS-10.15.6-x86_64-i386-64bit
```

#### Installation method
 - conda

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list | grep -E "rasterio|xarray|gdal"
libgdal                   3.0.4               h242383b_10    conda-forge
rasterio                  1.1.5            py38hac06332_1    conda-forge
rioxarray                 0.0.31                     py_0    conda-forge
xarray                    0.16.0                     py_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : raster
    active env location : /Users/bilelomrani/opt/miniconda3/envs/raster
            shell level : 2
       user config file : /Users/bilelomrani/.condarc
 populated config files : /Users/bilelomrani/.condarc
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.15.6
       base environment : /Users/bilelomrani/opt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/bilelomrani/opt/miniconda3/pkgs
                          /Users/bilelomrani/.conda/pkgs
       envs directories : /Users/bilelomrani/opt/miniconda3/envs
                          /Users/bilelomrani/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.8.5 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 501:20
             netrc file : /Users/bilelomrani/.netrc
           offline mode : False
```
</details>

**Comment by snowman2** [comment]
What about `raster = rioxarray.open_rasterio('no2_2019_01.tif', masked=True)`

**Comment by bilelomrani1** [comment]
Oh okay, I feel a bit embarrassed now ^^ It works perfectly, I thought it was expected to be the default behavior. Thanks!

**Comment by snowman2** [comment]
Glad to hear it works :+1: - no need to be embarrassed. I think the issue raised here is something worth looking into.

**Comment by brinda1410** [comment]
Per snowman2's comment, I had tried `raster = rioxarray.open_rasterio('no2_2019_01.tif', masked=True)`so it successfully worked for some images, but other images continue to display NaN in all the arrays. Is there a fix available for this issue?

**Comment by snowman2** [comment]
@brinda1410, if you are using the most recent version of rioxarray, please open a new issue with a re-producible example and environment information asked for in the bug template.
