### ISSUE TITLE
Save DataArray without coordinate information as geotiff (spatial) knowing crs and geotransform

### ISSUE THREAD

**Issue by marialucia81** [corteva/rioxarray#163]
Is it possible to store a DataArray without coordinate information (x,y) as geotiff?
I know crs and geotransform of data.

Thank you in advance

Maria Lucia

**Comment by snowman2** [comment]
https://corteva.github.io/rioxarray/stable/getting_started/manage_information_loss.html

I would use:
`rio.write_crs`
`rio.write_transform`
`rio.write_nodata`
and then:
`rio.to_raster`

**Comment by marialucia81** [comment]
It works fine. Thank you!
