### ISSUE TITLE
rio.clip() output differs if it is called with or without the drop option

### ISSUE THREAD

**Issue by marialucia81** [corteva/rioxarray#170]
Dear Developers,

in the following there are few lines of code, aiming to clip a raster, with or without the drop option.
I expect that, apart from the size of the output, the value of the pixels within the clip are identical.

```
from shapely.geometry import mapping
import geopandas as gpd
import rioxarray

geodf = gpd.read_file('castel_porziano.shp')
load_NDWI=rioxarray.open_rasterio('NDWI_full_scene_woc.tif')

clipped_df = load_NDWI.rio.clip(geodf.geometry.apply(mapping), geodf.crs, drop=False)
clipped_df.rio.to_raster('clipped_drop_false.tif')

clipped_dt = load_NDWI.rio.clip(geodf.geometry.apply(mapping), geodf.crs, drop=True)
clipped_dt.rio.to_raster('clipped_drop_true.tif')
```

The statistics of the two images are quite different (max and min) but I do not understand why there are pixels in the same clip with different values.

Here you can find the file I refer to in the code.

[CastelPorziano.zip](https://github.com/corteva/rioxarray/files/5308053/CastelPorziano.zip)
[clipped_drop_true.zip](https://github.com/corteva/rioxarray/files/5308054/clipped_drop_true.zip)
[clipped_drop_false.zip](https://github.com/corteva/rioxarray/files/5308055/clipped_drop_false.zip)
[NDWI_full_scene_woc.zip](https://github.com/corteva/rioxarray/files/5308052/NDWI_full_scene_woc.zip)

Thank you in advance,

Maria Lucia

#### Environment Information
```
rioxarray (0.1.0) deps:
rasterio: 1.1.6
xarray: 0.16.1
GDAL: 3.1.2

Other python deps:
scipy: 1.5.0
pyproj: 2.6.1.post1

System:
python: 3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 17:19:16) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\ml.magliozzi\AppData\Local\Continuum\anaconda3\envs\ses5g\python.exe
machine: Windows-10-10.0.18362-SP0
```

#### Installation method
 - conda

$ conda info

```
     active environment : ses5g
    active env location : C:\Users\ml.magliozzi\AppData\Local\Continuum\anaconda3\envs\ses5g
            shell level : 2
       user config file : C:\Users\ml.magliozzi\.condarc
 populated config files : C:\Users\ml.magliozzi\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\Users\ml.magliozzi\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\ml.magliozzi\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\ml.magliozzi\.conda\pkgs
                          C:\Users\ml.magliozzi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ml.magliozzi\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\ml.magliozzi\.conda\envs
                          C:\Users\ml.magliozzi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by snowman2** [comment]
I am not seeing the difference you are seeing when I ran the code on the original data:
![image](https://user-images.githubusercontent.com/8699967/94740132-b46c1980-0337-11eb-82c4-0d0de08c6282.png)
I opened in QGIS and tested some locations and they matched:
![image](https://user-images.githubusercontent.com/8699967/94740219-e0879a80-0337-11eb-8e34-f1ee74e63403.png)

What min/max do you see?

**Comment by marialucia81** [comment]
Thank you Alan,

there is something misleading in the histogram retrieval of the qgis
application, as you can see in the attached screenshots.

I am so sorry for reporting it.

Maria Lucia

[image: image.png]
[image: image.png]
[image: image.png]

Il giorno mer 30 set 2020 alle ore 23:14 Alan D. Snow <
notifications@github.com> ha scritto:

**Comment by snowman2** [comment]
That makes sense. Thanks for the report all the same. Better to look into it. 👍
