### ISSUE TITLE
Can the method rio.to_raster() applied to a Dataset manage multiple bands?

### ISSUE THREAD

**Issue by marialucia81** [corteva/rioxarray#171]
Dear Developers,

I create a dataset with some datavariables, immagine, in example different spectral indices of the same input scene.

Is the method rio.to raster() able to manage and save in the same tif dataset with multiple bands?

Thank you in advance.

Maria Lucia Magliozzi

**Comment by snowman2** [comment]
It can handle some things. See: https://corteva.github.io/rioxarray/stable/examples/convert_to_raster.html

If you need to save more complex data structures, I would recommend using `to_netcdf`.

**Comment by marialucia81** [comment]
Thank you Alan,

I have this dataset
`NDWI`
```
xarray.Dataset
Dimensions: x: 1293 y: 1251
Coordinates: spatial_ref () int32 0
Data variables: 
lon (y, x) float64 12.09 12.09 12.09 ... 12.57 12.57
lat (y, x) float64 41.9 41.9 41.9 ... 41.57 41.57
NDWI (y, x) float32 nan nan nan nan ... nan nan nan nan
Attributes: (0)
```
I save it with
`NDWI.rio.to_raster('NDWI_full_scene_lat_lon.tif')`

It seems to be stored or loaded as one band image
`prova=rioxarray.open_rasterio('NDWI_full_scene_lat_lon.tif')`

```
xarray.DataArray band: 1 y: 1251 x: 1293 [1617543 values with dtype=float32]
Coordinates: 
band (band) int32 1
y (y) float64 4.642e+06 4.642e+06 ... 4.605e+06
x (x) float64 2.585e+05 2.585e+05 ... 2.972e+05
spatial_ref () int32  0
Attributes: 
scale_factor : 1.0
add_offset : 0.0
long_name : Normalized Difference Water Index
grid_mapping : spatial_ref
```
There is the file attached.
[NDWI_full_scene_lat_lon.zip](https://github.com/corteva/rioxarray/files/5327545/NDWI_full_scene_lat_lon.zip)

Thank you in advance

Maria Lucia

**Comment by snowman2** [comment]
@marialucia81, that is expected that you lose the names of the bands when saving to a geotiff. If you want the data structure to be loaded in as close as possible to what was in the DataArray or Dataset, I would recommend using [to_netcdf](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_netcdf.html).

**Comment by snowman2** [comment]
If you have further questions, feel free to re-open or post more comments.
