### ISSUE TITLE
Issue in Merging/Mosaicing multiple images using Rioxarray Python

### ISSUE THREAD

**Issue by rrsc1234** [corteva/rioxarray#172]
Hi. I am using the following code to mosaic/merge 10 image files (.tif files) inside a folder using the following code:

`
import rioxarray
from rioxarray import merge
from rasterio.plot import show

items = [r'D:\LC08_L1TP_146046_20180425_20180502_01_T1.tif',
         r'D:\LE07_L1TP_145045_20180426_20180523_01_T1.tif',
         r'D:\LC08_L1TP_144046_20180427_20180502_01_T1.tif',
         r'D:\LC08_L1TP_144045_20180427_20180502_01_T1.tif',
         r'D:\LC08_L1TP_143046_20180420_20180502_01_T1.tif',
         r'D:\LC08_L1TP_143047_20180420_20180502_01_T1.tif',
         r'D:\LC08_L1TP_143045_20180420_20180502_01_T1.tif',
         r'D:\LE07_L1TP_145046_20180426_20180523_01_T1.tif',
         r'D:\LE07_L1TP_145045_20180426_20180523_01_T1.tif',
         r'D:\LC08_L1TP_144047_20180427_20180502_01_T1.tif']

elements = []

for val in items:
    elements.append(rioxarray.open_rasterio(val))
    
merged = merge.merge_arrays(elements, nodata=0.0)

image = merged.values
show(image)
`
After running the above code I am getting the following output:

![Rioxarray_Merge_image](https://user-images.githubusercontent.com/54926076/96083923-c32c0200-0edb-11eb-86e0-021a770af5c2.jpeg)

When I am loading all the input files (for mosaic/merge) in ArcMap, I am getting the following:

![input_files_in_arcmap](https://user-images.githubusercontent.com/54926076/96102445-29248380-0ef4-11eb-86cc-f979a449f4ef.jpg)

From the above 2 images it is observed that the mosaic image obtained after running the above code is flipped (left part and right side are swapped).

Can someone please let me know how to solve this issue.

I am attaching the link to the input files:
[https://drive.google.com/file/d/1hF5pb8MojW-N5l9xMgd1mJ95CtjLa8wQ/view?usp=sharing](url)

**Comment by snowman2** [comment]
@rrsc1234 are you able to share the input files? That would be the easiest way to be able to assist.

**Comment by snowman2** [comment]
I notice that you aren't using `merged.plot()`, what happens when you do that?

**Comment by rrsc1234** [comment]
> @rrsc1234 are you able to share the input files? That would be the easiest way to be able to assist.

@snowman2 . Here is the link to the input datasets:
[https://drive.google.com/file/d/1hF5pb8MojW-N5l9xMgd1mJ95CtjLa8wQ/view?usp=sharing](url)

**Comment by snowman2** [comment]
I see that you have both `EPSG:32643` and `EPSG:32644` as the CRS of the datasets. The merge function assumes that they are all the same CRS.

You need to change:
```python
for val in items:
    elements.append(rioxarray.open_rasterio(val))
```
to:
```python
for val in items:
    rds = rioxarray.open_rasterio(val)
    if rds.crs != "EPSG:32643":
        rds = rds.rio.reproject("EPSG:32643")
    elements.append(rds)
```

**Comment by snowman2** [comment]
Closing for preference to: https://gis.stackexchange.com/questions/376685/issue-while-performing-merge-mosaic-of-multiple-tiff-files-using-rioxarray-pytho/

**Comment by rrsc1234** [comment]
> I see that you have both `EPSG:32643` and `EPSG:32644` as the CRS of the datasets. The merge function assumes that they are all the same CRS.
> 
> You need to change:
> 
> ```python
> for val in items:
>     elements.append(rioxarray.open_rasterio(val))
> ```
> 
> to:
> 
> ```python
> for val in items:
>     rds = rioxarray.open_rasterio(val)
>     if rds.crs != "EPSG:32643":
>         rds = rds.rio.reproject("EPSG:32643")
>     elements.append(rds)
> ```

@snowman2 . Thanks for your suggestion. Your solution worked for me.

**Comment by snowman2** [comment]
Glad to hear that it worked 👍

**Comment by snowman2** [comment]
With fix in #183, targeted for the 0.2 release, this will be managed automatically.

**Comment by betolink** [comment]
Will this work for datasets opened with xarray? 

I tried to reproject a dataset into an adjacent UTM zone and the resulting grid was not aligned.

**Comment by snowman2** [comment]
> Will this work for datasets opened with xarray?
> I tried to reproject a dataset into an adjacent UTM zone and the resulting grid was not aligned.

If you are using the latest `rioxarray`, then I would recommend opening a new issue with the details of your problem.
