### ISSUE TITLE
Bug or user error - natural earth data issue with rioxarray

### ISSUE THREAD

**Issue by lwasser** [corteva/rioxarray#175]
Hi there -
i'm trying to update some of my lessons to use xarray and rioxarray for raster data processing. i previously used only rasterio.
i'm running into a quirk with natural earth data. I'm not sure if the issue has to do with the data or my approach. please let me know if you'd prefer this posted elsewhere! 

Below is a typical rasterio workflow and all is well. 
```
# Get terrain hillshade
terrain_hs = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/SR_HR.zip"

# Download and unzip natural earth data which contains state boundaries to generate AOI
#et.data.get_data(url=terrain_hs)

terrain_path = os.path.join(
    "earthpy-downloads", "SR_HR", "SR_HR", "SR_HR.tif")

# Open the data with rasterio
with rio.open(terrain_path) as src:
    hs = src.read(1)
    ext = plotting_extent(src)
    meta= src.profile

f, ax = plt.subplots()
ax.imshow(hs,
          cmap="Greys_r",
          extent=ext)
plt.show()
```

Here i use rioxarray - yay!
```
terrain_hs = rioxarray.open_rasterio(terrain_path)
# Looks good so far i think?
terrain_hs
```

This all looks ok (i'm working in a notebook hence the slightly odd print statements and such!)
```
print(terrain_hs.rio.crs, 
      terrain_hs.rio.bounds(),
      terrain_hs.rio.width,
      terrain_hs.rio.height)
terrain_hs.shape
```

Now i try to plot using rioxarray  - i've tried both `.plot` and `.plot.imshow()`
```
terrain_hs.plot.imshow()
```

the error that i'm getting is the typical matplotlib value error which i know is because the array is a 3 dimensional array (only one band)
```
ValueError: A 3-dimensional array was passed to imshow(), but there is no dimension that could be color.  At least one dimension must be of size 3 (RGB) or 4 (RGBA), and not given as x or y.
```
this also works so i know the data are generally ok... it's just the .plot method that is throwing things off.
```
# Plot with imshow
f, ax = plt.subplots()
ax.imshow(np.squeeze(terrain_hs.values))
plt.show()
```
i've tried:

* adding `col="band"` to the plot call
* converting from int to float
 
Should rioxarray plot single band rasters by default using .plot()? or am i doing something wrong in this workflow?
i do see the data are int 8bit rather than float but converting also doesn't help. 

thank you for any advice. it would be nice to not have to use the context managers that raster requires when teaching! students always get hung up on that element!

**Comment by snowman2** [comment]
I haven't looked at the file yet, but I wonder if the plot method in this example would work: https://corteva.github.io/rioxarray/stable/examples/COG.html

**Comment by snowman2** [comment]
I was able to get it to work like so:

```python
import rioxarray

rds = rioxarray.open_rasterio(terrain_path).squeeze()
rds.plot.imshow(cmap="Greys_r")
```

**Comment by lwasser** [comment]
@snowman2  THANK YOU!! ok so `squeeze()` must run numpy squeeze as it opens. i hadn't thought about looking more into built in methods. 

that worked for me perfectly. Thank you so much for the quick response! i will close this now. I really appreciate the simplicity of the code that rioxarray provides for raster operations. closing this!!
