### ISSUE TITLE
rioxarray export to_raster and CRS being dropped - user error or bug?

### ISSUE THREAD

**Issue by lwasser** [corteva/rioxarray#177]
hi there @snowman2 
I have a question about CRS persistence when you export a raster using rioxarray. It seems like when we begin to squeeze dimensions from the data, that the CRS gets dropped. I tried to reset the CRS before exporting to a geotiff but when i import the data the crs is not there as far as i can see.

Am i doing something incorrectly in the approach below? The CRS is that climate data global longitude values (no negatives). i'm not sure what the EPSG is for that one but we have the WKT definition from the original data. 

Any thoughts on what is incorrect? OR how i can ensure a CRS is set when exporting the data?

```
data_path = http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_macav2metdata_pr_BNU-ESM_r1i1p1_rcp45_2006_2099_CONUS_monthly.nc

# Open the data
with xr.open_dataset(full_file_path) as file_nc:
    climate_data_xr = file_nc

# CRS -- wkt format returned
climate_data_xr.rio.crs

# natural earth data - https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_1_states_provinces_lakes.zip
# Open the natural earth layer with geopandas
states_gdf = gpd.read_file(states_path)
# subset the data
cali_aoi = states_gdf[states_gdf.name == "California"]

# Get lat min, max for cali subset & convert to 0-360
aoi_lat = [float(cali_aoi.total_bounds[1]), float(cali_aoi.total_bounds[3])]
aoi_lon = [float(cali_aoi.total_bounds[0]), float(cali_aoi.total_bounds[2])]
aoi_lon[0] = aoi_lon[0] + 360
aoi_lon[1] = aoi_lon[1] + 360

# i'm using region mask to mask the data

state_mask = regionmask.mask_3D_geopandas(cali_aoi,
                                          climate_data_xr.lon,
                                          climate_data_xr.lat)

# Slice the data by time and spatial extent
start_date = "2010-01-15"
end_date = "2010-02-15"

# Subset the data by time and aoi & mask the data
climate_data_subset = climate_data_xr[climate_variable].sel(
    time=slice(start_date, end_date),
    lon=slice(aoi_lon[0], aoi_lon[1]),
    lat=slice(aoi_lat[0], aoi_lat[1])).where(state_mask)

#  This drops the 4th dimension which is region
new_masked_data = masked_data[:, :, :, 0]
# Reset the CRS given it gets dropped when you squeeze the data. 
new_masked_data.rio.set_crs(climate_crs)
# Save as new geotiff 
new_masked_data.rio.to_raster('subset_climate_raster_data.tif')

# reopen the data
saved_raster = xr.open_rasterio('subset_climate_raster_data.tif')
# The crs is empty now
saved_raster.rio.crs

```

**Comment by snowman2** [comment]
The CRS dropping is something difficult to avoid with xarray: https://corteva.github.io/rioxarray/stable/getting_started/crs_management.html

If you are not using `rioxarray.open_rasterio` the CRS is not guaranteed to be written in a persistent manner.
So, I recommend using `rio.write_crs` if you would like the CRS to persist on your dataset.

```python
with xr.open_dataset(full_file_path) as file_nc:
    climate_data_xr = file_nc.rio.write_crs(file_nc.rio.crs, inplace=True)
```

Side note: I recommend using `rio.clip` for masking (https://corteva.github.io/rioxarray/stable/examples/clip_geom.html). You can both mask with `drop=False` or clip with `drop=True` (default).

For example:
```python
from shapely.geometry import mapping
climate_data_subset = climate_data_xr.rio.clip(cali_aoi.geometry.apply(mapping), cali_aoi.crs).sel(time=slice(start_date, end_date)
```

Side note: The scripts are untested, so tweaks may be necessary.

**Comment by snowman2** [comment]
This page will likely be useful as well: https://corteva.github.io/rioxarray/stable/getting_started/manage_information_loss.html

**Comment by snowman2** [comment]
> \# Reset the CRS given it gets dropped when you squeeze the data. 
> new_masked_data.rio.set_crs(climate_crs)

This is a :bug:

**Comment by lwasser** [comment]
thank you again, @snowman2 !!
