### ISSUE TITLE
import of proj fails

### ISSUE THREAD

**Issue by Chrismarsh** [corteva/rioxarray#187]
#### Code Sample, a copy-pastable example if possible

This fails
```python
>>> from rasterio.warp import transform
>>> import rioxarray
```
with the error
```>>> import rioxarray # for xarray.rio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cbm038/.pyenv/versions/test/lib/python3.7/site-packages/rioxarray/__init__.py", line 8, in <module>
    import rioxarray.rioxarray  # noqa
  File "/home/cbm038/.pyenv/versions/test/lib/python3.7/site-packages/rioxarray/rioxarray.py", line 19, in <module>
    import pyproj
  File "/home/cbm038/.pyenv/versions/test/lib/python3.7/site-packages/pyproj/__init__.py", line 50, in <module>
    from pyproj import _datadir
ImportError: /home/cbm038/.pyenv/versions/test/lib/python3.7/site-packages/pyproj/_datadir.cpython-37m-x86_64-linux-gnu.so: undefined symbol: proj_context_set_autoclose_database
```

but if the import order is reversed, it succeeds

```python
>>> import rioxarray
>>> from rasterio.warp import transform
```
#### Problem description

This is occurring on a HPC machine that has multiple proj versions installed using the[ Lmod module system](https://www.tacc.utexas.edu/research-development/tacc-projects/lmod).

Presumably two different proj versions are getting loaded and thus the failure.
If I `import pyproj` prior to either of those two imports, it succeeds

#### Environment Information

 - rioxarray version (`python -c "import rioxarray; print(rioxarray.__version__)"`)

```rioxarray (0.1.1) deps:
  rasterio: 1.1.3
    xarray: 0.16.1
      GDAL: 3.0.1

Other python deps:
     scipy: 1.3.2
    pyproj: 2.6.1.post1

System:
    python: 3.7.4 (default, Jul 18 2019, 19:34:02)  [GCC 5.4.0]
executable: /home/cbm038/.pyenv/versions/test/bin/python
   machine: Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-redhat-7.8-Maipo```

 - rasterio version (`rio --version`)
1.1.3
 - GDAL version (`rio --gdal-version`)
3.0.1
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
3.7.4 (default, Jul 18 2019, 19:34:02)  [GCC 5.4.0]
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-redhat-7.8-Maipo

#### Installation method
 - pip install

**Comment by snowman2** [comment]
I would recommend ensuring you are using the same version of PROJ for both rasterio and pyproj.

This can be done with the `--no-binary` option or `PIP_NO_BINARY` environment variable when installing so they use the system PROJ instead of a wheel.

**Comment by Chrismarsh** [comment]
Thank you for confirming my worry. I've run more tests with `lsof` and I can confirm that I'm getting no less than three proj versions loaded, across a major revision (v6 and v7)! Various combinations of `--no-binary` for pyproj and rasterio did not work. I see that rasterio and pyproj are being provided froma local wheelhouse on the HPC machine I'm using, so I've opened a ticket with our sys admins to confirm the issue is on their end. I think safe to close this for now. Thank you very much!
