### ISSUE TITLE
clip->crop

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#21]
`crop` is probably the better name for clipping/cropping rasters.

**Comment by snowman2** [comment]
It seems GEE uses clip. Maybe `crop` could be an ailias for clip?

**Comment by djhoese** [comment]
What is GEE? Google Earth Engine? If you are going that route then what about numpy's `clip` which does something different...kind of?

**Comment by djhoese** [comment]
Ok just asked @dopplershift and his thought was:

1. if you don't have the data already then it would be subsetting
2. if you have the data and want to get a smaller chunk of data then it is cropping (manipulating data)
3. if you are drawing the data and only want to draw part of it then that is clipping

**Comment by snowman2** [comment]
I did a google search with `crop raster` and I had a mix of `crop` and `clip` show up. In QGIS & ArcGIS, they seem to like `clip` though:
- https://www.esri.com/arcgis-blog/products/product/analytics/clipping-an-image-or-raster-in-arcgis/
- https://pro.arcgis.com/en/pro-app/tool-reference/data-management/clip.htm
- http://www.qgistutorials.com/en/docs/raster_mosaicing_and_clipping.html

With clip in the `rio` namespace, I am thinking it shouldn't conflict with the [xarray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.clip.html) version of clip. 

```python
xds = xarray.open_rasterio("???")
xds.clip(...)
xds.rio.clip(...)
```

Thoughts?

**Comment by djhoese** [comment]
So the only thing I keep thinking is that all the tools you are talking about that use clipping are also visualizing the data. rioxarray isn't visualizing necessarily. I did some googling of "crop versus clip" and one thing that popped up was photoshop which uses crop as "anything outside this shape is removed" and clip as "anything outside this shape is hidden". Since rioxarray is returning a new object I'm not sure what the best name is for that, especially since it is likely a "view" of the original data.

Clip is fine.

**Comment by snowman2** [comment]
Random side note, just saw this: https://gis.stackexchange.com/questions/328128/extract-data-within-a-geometry-shape

**Comment by snowman2** [comment]
Also, based on this issue: https://github.com/pydata/xarray/issues/501, I am wondering if there should be an argument or something that only masks the data instead of clipping it. This is probably what you mean by the difference between `clip` and `crop`. However, with others being used to `clip`, I am concerned it would cause confusion in the transition between GEE, ArcGIS, and QGIS to `rioxarray`.

**Comment by snowman2** [comment]
Closing for now. If you have some other thoughts on the subject, feel free to continue.

**Comment by snowman2** [comment]
Just had a chuckle after remembering this discussion and connecting that corteva is an agricultural company ... `crop` should have been the obvious choice 😂
