### ISSUE TITLE
How to use rioxarray with xr.map_blocks?

### ISSUE THREAD

**Issue by cwerner** [corteva/rioxarray#213]
Hi

I currently try to create a feature mask (binary) for a large geotiff file using a shapefile containing region polygons...

My plan was to use `xr.map_blocks` to speed things up, but it seems that map_blocks does not preserve the rio  accessor? Is there any way to achieve this with the current library?

**Code sample**:  
```python
import geopandas as gpd
from shapely.geometry import mapping
import xarray as xr
import rioxarray

ds = rioxarray.open_rasterio("image.tif", chunks={'band': 3, 'x': 1024, 'y': 1024})
mask = xr.ones_like(ds.sel(band=1, drop=True), dtype='bool')

dtree = gpd.read_file("shapefile.shp")

def func(da):
    return da.rio.clip(dtree.geometry.apply(mapping), dtree.crs, drop=False)

mapped = xr.map_blocks(func, mask, template=mask.isel(y=0, x=0)).compute()
```

**Error:**  
```
<ipython-input-28-da3e85222d9f> in func()
      1 def func(da):
----> 2     return da.rio.clip(dtree.geometry.apply(mapping), dtree.crs, drop=False)

/opt/conda/lib/python3.6/site-packages/xarray/core/common.py in __getattr__()
    227                     return source[name]
    228         raise AttributeError(
--> 229             "{!r} object has no attribute {!r}".format(type(self).__name__, name)
    230         )
    231 

AttributeError: 'DataArray' object has no attribute 'rio'
```

**Comment by snowman2** [comment]
I wonder if you re-import `rioxarray` if it helps?
```python
def func(da):
    import rioxarray
    return da.rio.clip(dtree.geometry.apply(mapping), dtree.crs, drop=False)
```

**Comment by cwerner** [comment]
What the #@$#? The proposed change was actually the first thing I tried - but for some reason it did not make a difference. 

But now it actually works! I had to restart the jupyter kernel and now it works 🤷‍♂️ But unfortunately it is not taking advantage of my dask cluster (only using a single CPU core).

Seems like it's not able to process chunks in parallel? Is rioxarray not supporting dask arrays under the hood?

**Comment by snowman2** [comment]
Glad to hear that it worked :+1:

**Comment by snowman2** [comment]
I wonder if geocube might serve your use case better: https://github.com/corteva/geocube/

```python
import geopandas as gpd
import rioxarray
from geocube.api.core import make_geocube

dtree = gpd.read_file("shapefile.shp")
ds = rioxarray.open_rasterio("image.tif", chunks={'band': 3, 'x': 1024, 'y': 1024})
dtree["mask"] = 1

mask_grid = make_geocube(
    vector_data=dtree,
    measurements=["mask"],
    like=ds,
)
```
