### ISSUE TITLE
Python 3.6 Support

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#215]
From: https://github.com/conda-forge/rasterio-feedstock/pull/184#issuecomment-767161877

>  We are planning on adopting NEP 29 for all of conda-forge.

Python 3.6 support will be dropped in the community soon.

EOL is December 2021: https://devguide.python.org/#status-of-python-branches

**Comment by raybellwaves** [comment]
FYI xarray dropped support in 0.17.0 (http://xarray.pydata.org/en/stable/whats-new.html#breaking-changes)

**Comment by snowman2** [comment]
pyproj dropping support soon: https://github.com/pyproj4/pyproj/issues/790

**Comment by snowman2** [comment]
rasterio tracking issue: https://github.com/mapbox/rasterio/issues/2127

**Comment by ppgiii** [comment]
Hello,

Does anyone know how to run rioxarray in Colab?  Currently, Colab uses Python 3.6.9, not 3.7.

**Comment by snowman2** [comment]
@ppgiii, the latest release of `rioxarray` supports python 3.6, so you should be able to use that just fine. However, you will need to upgrade to python 3.7 to use future versions of `rioxarray` that don't support python 3.6.

**Comment by ppgiii** [comment]
Thanks, Colab just upgraded to 3.7.10 so the latest version installed.  Hopefully they will not drop me down back to 3.6.
