### ISSUE TITLE
BUG: Image missing tiles with dask write

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#220]
The image is corrupt (missing tiles).

![image](https://user-images.githubusercontent.com/1828519/105913916-2bb66f00-5ff3-11eb-8f22-338d74fcfde9.png)

_Originally posted by @djhoese in https://github.com/corteva/rioxarray/issues/219#issuecomment-767867834_

**Comment by snowman2** [comment]
From: https://github.com/corteva/rioxarray/pull/219#issuecomment-767960534
> From the SerializableLock docstring:
    This wraps a normal ``threading.Lock`` object and satisfies the same
    interface.  However, this lock can also be serialized and sent to different
    processes.  It will not block concurrent operations between processes (for
    this you should look at ``multiprocessing.Lock`` or ``locket.lock_file``
    but will consistently deserialize into the same lock.

Based on that I tried this and it worked:
```python
            mgr = multiprocessing.Manager()
            dask.array.store(
                out_dataarray.data.astype(dtype),
                self,
                lock=mgr.Lock(),
            )
```
It sounds like more research will be needed to find a suitable default and a `lock` kwarg will be needed in `to_raster`.

**Comment by djhoese** [comment]
I can confirm this works for me when I add a simple `lock` kwarg and pass it from the main script (that's what I was using to test the various options/solutions). I think we may need to get some dask developers in here on what is considered best practice or if there is a desired utility that can be added to dask for this. I'm concerned that this may work for the basic Client() which is still on one system, but won't work on a cluster or other multi-node dask scheduler.

I did some googling last night but didn't find anything about dask and multiprocess friendly locks.

**Comment by djhoese** [comment]
This kind of worked:

```
lock = dask.distributed.Lock("rio")
```

https://distributed.dask.org/en/latest/api.html?highlight=lock#distributed.Lock

But gave a lot of warnings when it exited:

```
/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/distributed/client.py:4832: RuntimeWarning: coroutine 'wait_for' was never awaited
  c.close(timeout=3)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/distributed/client.py:4832: RuntimeWarning: coroutine 'Client._close' was never awaited
  c.close(timeout=3)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/distributed/client.py:4832: RuntimeWarning: coroutine 'wait_for' was never awaited
  c.close(timeout=3)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by snowman2** [comment]
@TomAugspurger, is there documentation somewhere for best practices when using locks with dask?

**Comment by TomAugspurger** [comment]
I'll need to take a closer look at the implementation to give good guidance, but I'll attempt to give some general guidance before I take a look.

> I'm concerned that this may work for the basic Client() which is still on one system, but won't work on a cluster or other multi-node dask scheduler.

Yep, that sounds correct to me.

> @TomAugspurger, is there documentation somewhere for best practices when using locks with dask?

Not that I'm aware of. https://docs.dask.org/en/latest/array-creation.html#intermediate-storage would be a good home for it. But in general:

1. Locks are best avoided if possible (but if the underlying storage library isn't threadsafe, like HDF5 say, then they're unavoidable)
2. Fine-grained locks are probably best (i.e. the lock should be acquired as late as possible, in the task writing a single chunk)
3. Consider how the lock interacts with the scheduler (threading.Lock for the threaded scheduler, multiprocessing Lock for the processes scheduler, etc.)

I'll take a look at the example later today.

**Comment by snowman2** [comment]
Thanks @TomAugspurger, that was helpful. I will need to look into it a bit more.

**Comment by snowman2** [comment]
Example posted: https://corteva.github.io/rioxarray/latest/examples/dask_read_write.html

If you see any issues with it or have recommendations, please let me know.

**Comment by djhoese** [comment]
Typo on "distributed': https://corteva.github.io/rioxarray/latest/examples/dask_read_write.html#No-distrubuted-computing-example

**Comment by djhoese** [comment]
Oh and can't the `lock` be provided to the reading portion so the `.persist()` isn't needed?

**Comment by snowman2** [comment]
> Oh and can't the lock be provided to the reading portion so the .persist() isn't needed?

I tested it out and that is the case. Thanks for that :+1:
