### ISSUE TITLE
REF: Reduce pyproj CRS usage for speed

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#241]
Usage of the `pyproj.CRS` class internally slows things down quite a bit:
https://github.com/corteva/rioxarray/discussions/234

It is there for 2 reasons:
1. #92 (GDAL 2/3 compatibility)
2. #124 (Write CF parameters)

Since `rasterio` now has GDAL 3 in the wheels, reason 1 is now less important. Writing the full CF parameters are only useful for those using `to_netcdf`. For those not using that, it only slows them down.

I think the solution is in two parts:
1. Reduce usage of `pyproj.CRS` and rely more on `rasterio.crs.CRS`
2. Add option to disable writing CF parameters using `pyproj.CRS` and only include WKT parameters.

**Comment by djhoese** [comment]
Just curious, what is the cause of the slow down? Conversion to/from pyproj CRS and rasterio CRS? Or is the pyproj CRS inherently slower for CRS operations?

**Comment by snowman2** [comment]
Related to: https://github.com/pyproj4/pyproj/issues/661

With `to_cf` you create several different objects with it's own context, and that slows things down quite a bit. It also incurs hits from opening and closing connections to the database. If you use the global context, then you get quite a bit of speed improvements as you only have one database connection and you don't create a new context each time.

It is only really an issue if you are iterating over many files.

**Comment by djhoese** [comment]
@snowman2 Being the pyproj maintainer, what would you recommend for a library like Satpy where we want to use pyproj CRS objects in all of our DataArrays? Maybe store the WKT instead and convert to CRS objects when needed?

**Comment by snowman2** [comment]
> what would you recommend for a library like Satpy

If they are re-used often, then storing the CRS object can reduce the number of contexts being re-generated. But, I would recommend testing things out to see what works best as the results of that will give a better idea of what works for your workflows.

**Comment by djhoese** [comment]
We have our normal workflows which may be ~16 DataArrays objects with a pyproj CRS for each (should be the same initial CRS object shared between them). But in some workflows people might be going through time steps of data so 16 * number of times. Each time step of images, just based on the structure of Satpy, will have a new CRS object. I'll have to keep this in mind as we profile Satpy more for these cases. I think we plan on following rioxarrays lead as much as possible but use only pyproj CRS and no rasterio.
