### ISSUE TITLE
CRS setting and copying

### ISSUE THREAD

**Issue by Meresmata** [corteva/rioxarray#252]
I try to set the crs, and than to copy the raster. Turns out the self set crs, isn't copied.:

The functions for copying I use are  write_crs and set_crs. Both give different results.

```python
raster = open_rasterio(r"PATH\FILENAME.xyz")  # No crs set
raster.rio.write_crs(32633)  # crs is None 
raster.rio.set_crs(32633)  # result: CRS.from_epsg(32633)

crs = CRS("EPSG:32633")
raster.rio.write_crs(crs.to_wkt())  #  None
raster.rio.set_crs(crs.to_wkt())  # result: CRS.from_epsg(32633)

# when copiing the raster
raster.rio.crs  # CRS.from_epsg(32633)
r1 = raster.copy()
r1.rio.crs  # None
```
#### Problem description

The copy method only copies the original data, not the changed?

#### Environment Information
rioxarray (0.2.0) deps:
  rasterio: 1.2.0
    xarray: 0.16.2
      GDAL: 3.1.4

Other python deps:
     scipy: 1.6.0
    pyproj: 3.0.0.post1

System:
    python: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 22:54:47) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\remote\anaconda3\envs\PROJEKTNAME\python.exe
   machine: Windows-10-10.0.19041-SP0

#### Installation method
 - conda-forge

**Comment by snowman2** [comment]
If you want to be able to copy and have the CRS persist, you need to use `rio.write_crs`. Nothing can be done in `rioxarray` if you use `rio.set_crs`. Hopefully that gets you where you need to be.

**Comment by snowman2** [comment]
I noticed you have `raster.rio.write_crs(crs.to_wkt())`, so my previous comment was only partially helpful.

You need to either:
1. Use `inplace=True`
```python
raster.rio.write_crs(crs, inplace=True)
```
2. Set the new variable with the copy:

```python
raster = raster.rio.write_crs(crs)
```

**Comment by snowman2** [comment]
For those finding this issue, I recommend reading the [Getting Started: Introductory Information](https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html#introductory-information) references for rioxarray. The [Coordinare Reference System Management](https://corteva.github.io/rioxarray/stable/getting_started/crs_management.html) section is relevant for this issue.
