### ISSUE TITLE
open_rasterio throws AttributeError after updating new xarray version 0.17.0

### ISSUE THREAD

**Issue by bidhya** [corteva/rioxarray#254]
rioxarray.open_rasterio(raster) was working fine. Today I updated xarray to the new release 0.17.0 and now rioxarray.open_rasterio thows an AttributeError

#### Code Sample, a copy-pastable example if possible
```python
rioxarray.open_rasterio(f'{maskdir}/{mask_tif}')


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/lib/python3.8/site-packages/xarray/core/common.py in __setattr__(self, name, value)
    267         try:
--> 268             object.__setattr__(self, name, value)
    269         except AttributeError as e:

AttributeError: 'DataArray' object has no attribute '_file_obj'

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-93443f96a841> in <module>
      5 print(mask_tif)
      6 # Extract the water mask and set background to nan
----> 7 mask = rioxarray.open_rasterio(f'{maskdir}/{mask_tif}')

~/miniconda3/lib/python3.8/site-packages/rioxarray/_io.py in open_rasterio(filename, parse_coordinates, chunks, cache, lock, masked, mask_and_scale, variable, group, default_name, **open_kwargs)
    866 
    867     # Make the file closeable
--> 868     result._file_obj = manager
    869 
    870     return result

~/miniconda3/lib/python3.8/site-packages/xarray/core/common.py in __setattr__(self, name, value)
    274             ):
    275                 raise
--> 276             raise AttributeError(
    277                 "cannot set attribute %r on a %r object. Use __setitem__ style"
    278                 "assignment (e.g., `ds['name'] = ...`) instead of assigning variables."

AttributeError: cannot set attribute '_file_obj' on a 'DataArray' object. Use __setitem__ styleassignment (e.g., `ds['name'] = ...`) instead of assigning variables.
```

#### Environment Information
Tested on Linux  
rioxarray                 0.3.0              conda-forge
xarray                    0.17.0             conda-forge

</details>

**Comment by dcherian** [comment]
cc @snowman2

**Comment by dcherian** [comment]
it'd be nice if rioxarray could test against the git master version of xarray to catch these things before release.

**Comment by snowman2** [comment]
> it'd be nice if rioxarray could test against the git master version of xarray to catch these things before release.

Agreed.

**Comment by snowman2** [comment]
Related: https://github.com/pydata/xarray/pull/4809

**Comment by snowman2** [comment]
@dcherian do you know what the recommended method for accessing the underlying file object in `xarray` is now?

We use it in a couple of places. For example:
- `to_raster` to get the profile [ref](https://github.com/corteva/rioxarray/blob/0804791a44f65ac4f303dd286e94b3eaee81f72b/rioxarray/raster_array.py#L877)
- `nodata` to get the nodata value [ref](https://github.com/corteva/rioxarray/blob/0804791a44f65ac4f303dd286e94b3eaee81f72b/rioxarray/raster_array.py#L281)
- `clip` to clip from disk [ref](https://github.com/corteva/rioxarray/blob/0804791a44f65ac4f303dd286e94b3eaee81f72b/rioxarray/raster_array.py#L139)

**Comment by snowman2** [comment]
https://github.com/pydata/xarray/issues/2550. To be consistent, could add the filename in `encoding["source"]`. However, this isn't always helpful. For example `WarpedVRT`.

**Comment by dcherian** [comment]
> @dcherian do you know what the recommended method for accessing the underlying file object in xarray is now?

I don't. cc @shoyer @jhamman @aurghs @alexamici

**Comment by snowman2** [comment]
I have a patch in #255. Plan on adding the latest xarray to the CI soon.

**Comment by alexamici** [comment]
I confirm that #255 looks correct. Thanks and sorry for the breakage.

Note that next release of *xarray* will include the new backend API with some changes that may impact you.
