### ISSUE TITLE
Unreleased version of xarray (0.18) breaks things

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#260]
https://github.com/corteva/rioxarray/runs/1990677174?check_suite_focus=true

`test_to_raster` fails with:
```
AttributeError: 'DataArray' object has no attribute 'values'
```
`test_to_raster__dataset__mask_and_scale` fails with:
```
IndexError: too many indices
```

**Comment by djhoese** [comment]
Possibly related: https://github.com/pydata/xarray/issues/4934

**Comment by robmarkcole** [comment]
I can report a similar error, although xarray is functioning without issue. 

```
AttributeError: cannot set attribute '_file_obj' on a 'DataArray' object. Use __setitem__ styleassignment (e.g., `ds['name'] = ...`) instead of assigning variables.
```

```
xarray==0.17.0
rioxarray==0.3.0
```

**Comment by snowman2** [comment]
#254 is what you are experiencing. This has been addressed in the 0.3.1 release.

**Comment by robmarkcole** [comment]
Can confirm, thanks @snowman2

**Comment by alexamici** [comment]
@snowman2 another breakage come from the rename of `LazilyOuterIndexedArray ` to `LazilyIndexedArray` un `master` https://github.com/pydata/xarray/issues/5111 

Note that I already proposed a PR to keep the old name around to ease the migration: https://github.com/pydata/xarray/pull/5112

**Comment by snowman2** [comment]
@alexamici, thanks for your help getting things working again :+1:
