### ISSUE TITLE
add example of write_crs

### ISSUE THREAD

**Issue by raybellwaves** [corteva/rioxarray#262]
There is an example of [`write_crs`](https://github.com/corteva/rioxarray/blob/master/rioxarray/rioxarray.py#L289) here: https://gis.stackexchange.com/questions/354782/how-to-mask-netcdf-time-series-data-from-a-shapefile-in-python/354798#354798

It could be added as as example to the doc string

**Comment by snowman2** [comment]
This is a great idea. Thanks for submitting a PR :+1:
