### ISSUE TITLE
in `clip` use the crs from the geopandas dataframe

### ISSUE THREAD

**Issue by raybellwaves** [corteva/rioxarray#264]
In https://github.com/corteva/rioxarray/discussions/259 I learned you have to specify the `crs` for the xarray object. There may be times where you can specify the crs from the geo pandas dataframe e.g. `clip(geometry, crs)`. You can specific the `crs` manually by doing `ds.rio.write_crs("epsg:4326")`. Given that the `crs` is input into the function is there a way to parse that though to the xarray object if it doesn't have a crs? I understand this may be quite risky for the user if the crs isn't desired.

An alternative I can think of is the parse the geopandas dataframe crs in the `MissingCRS` e.g. CRS not found. Clipping using a geopandas dataframe which a crs: {gdf.crs} ... you can set crs using rio.write_crs({gdf.crs})

**Comment by snowman2** [comment]
For reference, from the `Getting Started` page, you can find a page on Coordinate Reference System (CRS) Management [ref](https://corteva.github.io/rioxarray/stable/getting_started/crs_management.html).

> There may be times where you can specify the crs from the geo pandas dataframe e.g. clip(geometry, crs)

In `rio.clip` the `crs` kwarg is the CRS of the geometries used for clipping, not the CRS of the xarray dataset ([ref](https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray.raster_array.RasterArray.clip)). It is there to transform the geometries to the CRS of the `xarray` object if it is different.

> is there a way to parse that though to the xarray object if it doesn't have a crs?

`rioxarray` searches for the CRS using the CF conventions 1.8 and also looks for the `crs` attribute for compatibility with `xarray.open_rasterui`:
https://github.com/corteva/rioxarray/blob/204938407c7ebf24172da4888316cedbea65c1f1/rioxarray/rioxarray.py#L148-L180

**Comment by snowman2** [comment]
> Given that the crs is input into the function is there a way to parse that though to the xarray object if it doesn't have a crs?

No. That is the CRS of the geometries. It is better to keep those separate.

**Comment by raybellwaves** [comment]
Thanks a lot for the links and your thoughts. Closing
