### ISSUE TITLE
create ci folder?

### ISSUE THREAD

**Issue by raybellwaves** [corteva/rioxarray#265]
Could add a ci folder which contains yaml files for the development environment. This matches xarray and may make it easier for xarray developers to develop here as well: http://xarray.pydata.org/en/stable/contributing.html#creating-a-python-environment

**Comment by snowman2** [comment]
We have and [environment.yml](https://github.com/corteva/rioxarray/blob/master/environment.yml) for conda environments. If you wanted to remove the `python` pin, you would be able to use that similar to how `xarray` uses it.

Our CI doesn't use environment files for managing the environments as it just specifies the dependencies. This is often more stable than the methods they are proposing (at least it has been in the past in my experience).

**Comment by snowman2** [comment]
https://github.com/corteva/rioxarray/blob/22251db2df18201f707ca5560bafb3def61d1212/.github/workflows/tests.yaml#L56
