### ISSUE TITLE
Keep in memory original data type for writing

### ISSUE THREAD

**Issue by remi-braun** [corteva/rioxarray#305]
It could be very nice to keep in memory the original data type (ie. `uint16` for landsat data or `uint8` for classified data).

Indeed, for now (unless I missed something), if we open a dataset with `masked=True` and the data is casted to float, we lose the information of the original datatype.
So we always write the dataset on disk in float, even when it is not justified (when the nodata is replaced by its true value)

**Comment by snowman2** [comment]
That is a really good idea. I think this discussion should start with xarray to ensure consistency.

**Comment by snowman2** [comment]
Seems related: https://github.com/pydata/xarray/issues/4973

**Comment by snowman2** [comment]
This seems more relevant: https://github.com/pydata/xarray/issues/1194

**Comment by dcherian** [comment]
You should be able to set `.encoding["dtype"]` at write time.

I bet it's being saved in `encoding` at read time but then is lost later.

**Comment by snowman2** [comment]
Fix in #306
