### ISSUE TITLE
Discrepancy between clip methods

### ISSUE THREAD

**Issue by remi-braun** [corteva/rioxarray#310]
#### Code Sample, a copy-pastable example if possible
Shapes:
[raster_mask.zip](https://github.com/corteva/rioxarray/files/6349786/raster_mask.zip)

Raster:
[raster.zip](https://github.com/corteva/rioxarray/files/6349787/raster.zip)

```python
>>> xda = rioxarray.open_rasterio("raster.tif")
>>> shapes = gpd.read_file("raster_mask.geojson")
>>> A = xda.rio.clip(shapes.geometry, from_disk=True)
>>> B = xda.rio.clip(shapes.geometry, from_disk=False)
>>> A.shape
(1, 321, 363)
>>> B.shape
(1, 320, 361)
```
#### Problem description

The `rasterio` mask method gives another result than the default clip behavior.
The discrepancy stands in the border, 1 (or 0) pixels are added with the rasterio method:
![2021-04-21_11h50_08](https://user-images.githubusercontent.com/67311115/115534288-ede68100-a297-11eb-8b4c-64ef55c8b478.png)

#### Expected Output
Same shape

#### Environment Information
rioxarray (0.3.1) deps:
  rasterio: 1.2.3
    xarray: 0.17.0
      GDAL: 3.2.2
Other python deps:
     scipy: 1.6.2
    pyproj: 3.0.1
System:
    python: 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:47:31) [MSC v.1900 64 bit (AMD64)]
executable: C:\Users\rbraun\Anaconda3\envs\sertit\python.exe
   machine: Windows-10-10.0.19041-SP0

#### Installation method
 - pypi

**Comment by snowman2** [comment]
This is a known issue. Both methods are powered by different methods in rasterio:

From disk uses `rasterio.mask.mask`: https://github.com/corteva/rioxarray/blob/4d19b056f61d767c7863a4ff1a7858edebe82f5c/rioxarray/raster_array.py#L137

The default clip uses `geometry_mask`:
https://github.com/corteva/rioxarray/blob/4d19b056f61d767c7863a4ff1a7858edebe82f5c/rioxarray/raster_array.py#L166

**Comment by remi-braun** [comment]
Ok my bad 😄 
I think this discrepancy in term of shape should be documented in the clip example

**Comment by snowman2** [comment]
It may be worthwhile to ask if this behavior is expected and why it adds the padding upstream (https://github.com/mapbox/rasterio/).

**Comment by snowman2** [comment]
> I think this discrepancy in term of shape should be documented in the clip example

Yes, it would be good to note the difference.
