### ISSUE TITLE
Access violation when opening a file

### ISSUE THREAD

**Issue by remi-braun** [corteva/rioxarray#322]
#### Code Sample, a copy-pastable example if possible

Data: 
[07_20191215T110441_S2_T30TXP_L2A_122756_PRED.zip](https://github.com/corteva/rioxarray/files/6403390/07_20191215T110441_S2_T30TXP_L2A_122756_PRED.zip)

```python
import rasterio, xarray, rioxarray
rasterio.open(r"07_20191215T110441_S2_T30TXP_L2A_122756_PRED.tif") # OK
xarray.open_rasterio(r"07_20191215T110441_S2_T30TXP_L2A_122756_PRED.tif") # OK
rioxarray.open_rasterio(r"07_20191215T110441_S2_T30TXP_L2A_122756_PRED.tif")  # Fails: Process finished with exit code -1073741819 (0xC0000005)
```
#### Problem description

File that seems corrupted when read with `rioxarray` but is fine with any other read method (`rasterio`, `xarray`, `QGIS`, `ArcGis`) 
The run breaks with error `Fails: Process finished with exit code -1073741819 (0xC0000005)` that seems to mean `Access Violation`.

#### Expected Output

Opening without failure

#### Environment Information

rioxarray (0.3.1) deps:
  rasterio: 1.2.3
    xarray: 0.17.0
      GDAL: 3.2.2
Other python deps:
     scipy: 1.6.3
    pyproj: 3.0.1
System:
    python: 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:47:31) [MSC v.1900 64 bit (AMD64)]
executable: C:\Users\rbraun\Anaconda3\envs\extracteo\python.exe
   machine: Windows-10-10.0.19041-SP0

#### Installation method
pypi

**Comment by snowman2** [comment]
I am not seeing this issue for some reason:
```python
import rioxarray
rxr = rioxarray.open_rasterio("07_20191215T110441_S2_T30TXP_L2A_122756_PRED.tif")
print(rxr)
rioxarray.show_versions()
```
```bash
python debug.py 
<xarray.DataArray (band: 1, y: 5490, x: 5490)>
[30140100 values with dtype=uint8]
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 6e+05 6e+05 6.000e+05 ... 7.098e+05 7.098e+05
  * y            (y) float64 4.9e+06 4.9e+06 4.9e+06 ... 4.79e+06 4.79e+06
    spatial_ref  int64 0
Attributes:
    _FillValue:    255.0
    scale_factor:  1.0
    add_offset:    0.0
rioxarray (0.3.2.dev0) deps:
  rasterio: 1.2.2
    xarray: 0.17.0
      GDAL: 3.2.1

Other python deps:
     scipy: 1.6.2
    pyproj: 3.0.1

System:
    python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)  [GCC 9.3.0]
executable: ~/miniconda/envs/rioxarray/bin/python
   machine: Linux-5.4.0-72-generic-x86_64-with-glibc2.10
```
My current guess is that you installed from pypi when you are using conda. I would recommend not mixing the two and instead try this to see if it helps:
```bash
conda create -n rio -c conda-forge rioxarray
conda activate rio
python debug.py
```

**Comment by remi-braun** [comment]
I installed everything via `pip` inside a conda package, the only way I found to mix geopandas and rasterio on Windows easily (I cannot use virtualenv).
I had no error so far (for more than a year).

You know from where it might come from ?

**Comment by snowman2** [comment]
I would highly recommend using the `conda-forge` channel to install everything. It works well to install rasterio/geopandas together. If you mix conda with pip, strange things tend to happen.

If you want to debug your current environment, usually I would recommend `gdb` if you are able (if you are using WSL2) [ref](https://pandas.pydata.org/docs/development/debugging_extensions.html). Since you aren't using a unix-like environment, then I am not sure how you would debug. Likely would need to use a search engine to see if you can find a C debugger for Windows.

**Comment by snowman2** [comment]
https://conda-forge.org/docs/user/tipsandtricks.html
```
$ cat .condarc
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

**Comment by remi-braun** [comment]
That was my initial way of doing it on windows but I stopped it (and used the nice Gohlke's wheels) because everytime I did a `conda update`, my env brake... 
I know that installing together these libs works but does is it still for you to:
- create first the env
- then install rasterio 
- and then geopandas ?

Maybe they improved something since my last try...

**Comment by snowman2** [comment]
> everytime I did a conda update, my env brake

I usually create a new environment every time and haven't had many troubles with that. Updating caused me issues historically as well.

> I know that installing together these libs works but does is it still for you to:

I would install them together if possible. But, I haven't had any issues installing geopandas after rasterio.

**Comment by remi-braun** [comment]
OK nice feedback, thanks :)

**Comment by snowman2** [comment]
@remi-braun did using conda resolve your issues?

**Comment by remi-braun** [comment]
I haven't tested, I have rewritten my code in a way that works 😛

**Comment by snowman2** [comment]
Nice :+1:  In that case, I will close this issue. Feel free to add comments/reopen if it isn't resolved.
