### ISSUE TITLE
overview not read when specifying chunks or lock

### ISSUE THREAD

**Issue by allredbw** [corteva/rioxarray#344]
#### Code Sample, a copy-pastable example if possible

```python
import rasterio
import rioxarray

# from https://openaerialmap.org/
cog_url = (
    "https://oin-hotosm.s3.amazonaws.com/"
    "5d7dad0becaf880008a9bc88/0/5d7dad0becaf880008a9bc89.tif"
)
```

```python
ds = rioxarray.open_rasterio(cog_url, lock=False, chunks=(4, "auto", -1))
ds.shape
```

    (3, 9984, 22016)

```python
dsLockChunksOverview = rioxarray.open_rasterio(cog_url, lock=False, chunks=(4, "auto", -1), overview_level=1)
dsLockChunksOverview.shape
```

    (3, 9984, 22016)

```python
dsChunksOverview = rioxarray.open_rasterio(cog_url, chunks=(4, "auto", -1), overview_level=1)
dsChunksOverview.shape
```

    (3, 9984, 22016)

```python
dsLockOverview = rioxarray.open_rasterio(cog_url, lock=False, overview_level=1)
dsLockOverview.shape
```

    (3, 9984, 22016)

```python
dsOverview = rioxarray.open_rasterio(cog_url, overview_level=1)
dsOverview.shape
```

    (3, 2496, 5504)

#### Problem description

Large COGs consequently have large overviews. It may be beneficial to read the overview in parallel without locks, as documented in [Reading COGs in Parallel](https://corteva.github.io/rioxarray/stable/examples/read-locks.html). Perhaps this behavior is documented, but I could not find it.

#### Expected Output

The correct shape of the overview `(3, 2496, 5504)` when specifying `overview_level` AND `chunks` or `lock`.

#### Environment Information

rioxarray (0.4.0) deps:
  rasterio: 1.2.3
    xarray: 0.18.2
      GDAL: 3.2.2

Other python deps:
     scipy: 1.6.3
    pyproj: 3.0.1

System:
    python: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
executable: /usr/bin/python3
   machine: Linux-5.4.104+-x86_64-with-debian-10.9

#### Installation method
pypi

**Comment by snowman2** [comment]
Thanks for the report :+1:

**Comment by allredbw** [comment]
Thank you for the quick fix!

**Comment by allredbw** [comment]
@snowman2 Was this included in 0.4.1.post0? An update and quick test reveals the same shape as no overview, just as before.

```
dsLockChunksOverview = rioxarray.open_rasterio(cog_url, lock=False, chunks=(4, "auto", -1), overview_layer=1)
dsLockChunksOverview.shape
```

```
(3, 9984, 22016)
```

```
dsOverview = rioxarray.open_rasterio(cog_url, overview_level=1)
dsOverview.shape
```

```
(3, 2496, 5504)
```

rioxarray (0.4.1.post0) deps:
  rasterio: 1.2.3
    xarray: 0.18.0
      GDAL: 3.2.2

Other python deps:
     scipy: 1.4.1
    pyproj: 3.1.0

System:
    python: 3.7.10 (default, May  3 2021, 02:48:31)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.109+-x86_64-with-Ubuntu-18.04-bionic

**Comment by snowman2** [comment]
Yep, it is there. Watch out for the typo: `overview_layer` should be `overview_level`.

**Comment by allredbw** [comment]
Yes, my mistake. Thank you!

```
dsLockChunksOverview = rioxarray.open_rasterio(cog_url, lock=False, chunks=(4, "auto", -1), overview_level=1)
dsLockChunksOverview.shape
```

```
(3, 2496, 5504)
```
