### ISSUE TITLE
Allow control of window routing in clip_box

### ISSUE THREAD

**Issue by ricardog** [corteva/rioxarray#354]
When clipping a raster with `clip_box()`, I would like to have control over how the window is rounded (or not). [rasterio](https://github.com/mapbox/rasterio) provides two methods for rousing the offsets and the lengths of a window ([round_lengths](https://github.com/mapbox/rasterio/blob/master/rasterio/windows.py#L676) and [round_offsets](https://github.com/mapbox/rasterio/blob/master/rasterio/windows.py#L708)) which allow passing in the operator used to round the values.

Say, for example, that I clip a 0.25° raster with the bounds

```python
BoundingBox(left=-179.14733875399997, bottom=-14.373764999999935, right=179.77848000000006, top=71.38961029100003)
```

The resulting window is

```python
Window(col_off=3.4106449840001005, row_off=74.4415588359999, width=1435.7032750160001, height=343.05350116399984)
```

I would like to be able to round that to

```python
Window(col_off=3, row_off=74, width=1436, height=344)
```

I can accomplish want with the current code by doing

```python
    win1 = rasterio.windows.from_bounds(*bounds, transform)
    win2 = win.round_offsets('floor').round_lengths('ceil')
    aligned_bounds = rasterio.windows.bounds(win2, transform)
   array.rio.clip_box(*aligned_bounds)
```

but it would be nicer to have rioxarray allow me to specify the rousing.

Thanks!

**Comment by snowman2** [comment]
I think you may be interested in the [rio.isel_window](https://github.com/corteva/rioxarray/blob/6204661cc9a703307207f548365b020a2d6eac59/rioxarray/rioxarray.py#L897-L936) method.

Your code would look like:
```python
from rasrerio.window import from_bounds

array.rio.isel_window(
    from_bounds(
        *bounds, array.rio.transform()
    ).round_offsets('floor').round_lengths('ceil')
)
```

**Comment by snowman2** [comment]
> I would like to have control over how the window is rounded (or not).

Unfortunately, `rioxarray` does not support decimated reading at this time. Due to this, the row/col are rounded in `isel_window`./`clip_box` using the outer limits of the rows.

If you want to look into adding adjustments for the window (round_lengths/round_offsets) kwargs in `clip_box`, I would be open to it.

**Comment by ricardog** [comment]
> I think you may be interested in the [rio.isel_window](https://github.com/corteva/rioxarray/blob/6204661cc9a703307207f548365b020a2d6eac59/rioxarray/rioxarray.py#L897-L936) method.

Thanks, this works for me. I'm not trying to do decimated reads, I want to avoid unaligned pixels (which is what I think you get with non-integer window boundaries).

**Comment by snowman2** [comment]
> Thanks, this works for me.

Sounds good. If I understand correctly, `isel_window` resolved this issue for you and no further action is needed?

**Comment by ricardog** [comment]
Yes, `isle_window` works for me. Thanks.
