### ISSUE TITLE
BUG: COG driver overview_level all 0s when writing

### ISSUE THREAD

**Issue by andhuang-CLGX** [corteva/rioxarray#410]
```
import datetime
import rioxarray
from dask.distributed import Lock, Client


url = (
    "https://naipeuwest.blob.core.windows.net/naip/v002/md/2013/md_100cm_2013/"
    "39076/m_3907617_ne_18_1_20130924.tif"
)

s = datetime.datetime.utcnow()
with Client(n_workers=1, threads_per_worker=4) as client:
    ds = rioxarray.open_rasterio(url, lock=False, chunks="auto", num_threads=4)
    ds.rio.to_raster(
        "test.tif", driver="COG", tiled=True, lock=Lock("rio", client),
        num_threads=4, bigtiff=True, resampling="average", overview_resampling="average"
    )
e = datetime.datetime.utcnow()
print(e - s)
```

`rioxarray.open_rasterio("test.tif", overview_level=2).mean()`
results in 0.

**Comment by andhuang-CLGX** [comment]
Only happens when using dask.

**Comment by snowman2** [comment]
I am not sure that the `COG` driver and dask work well together. The reason is that GDAL needs the entire raster to be able to properly chunk and generate overviews. With dask, the chunks are written separately. This works well for the `GTiff` driver when you are creating a tiled raster, but it may not be possible to do with all drivers.

**Comment by andhuang-CLGX** [comment]
Is there another way to create overviews besides COG in rioxarray? (equivalent of gdaladdo)

**Comment by snowman2** [comment]
> Is there another way to create overviews besides COG in rioxarray?

You would likely have to use something like the feature requested in #204 | #309 and then use rasterio.

**Comment by andhuang-CLGX** [comment]
`gdal_translate -of COG initial.tif final.tif -co NUM_THREADS=32 -co TILED=YES -co RESAMPLING=AVERAGE -co COMPRESS=LZW -co PREDICTOR=2` Ok I think maybe mroe straightforward to use this command

**Comment by snowman2** [comment]
Thanks for the report :+1: . Closing as I think there isn't much rioxarray can do for this due to the nature of the COG driver. It will likely need to be handled by GDAL.

**Comment by andhuang-CLGX** [comment]
Maybe adding a warning?

**Comment by snowman2** [comment]
> Maybe adding a warning?

If you would like to add a warning for dask users with the COG driver, a PR would be welcome.

**Comment by snowman2** [comment]
https://gdal.org/drivers/raster/cog.html

I am wondering if it works with dask if you use: OVERVIEWS=IGNORE_EXISTING?
```
    ds.rio.to_raster(
        "test.tif", 
        driver="COG",
        tiled=True,
        lock=Lock("rio", client),
        num_threads=4,
        bigtiff=True,
        resampling="average",
        overview_resampling="average",
        overviews="IGNORE_EXISTING",
    )
```

**Comment by snowman2** [comment]
> I am wondering if it works with dask if you use: OVERVIEWS=IGNORE_EXISTING?

That doesn't appear to do anything.

**Comment by RichardScottOZ** [comment]
Ok, this I had not seen, how many overview levels were in the original here?

**Comment by RichardScottOZ** [comment]
> `gdal_translate -of COG initial.tif final.tif -co NUM_THREADS=32 -co TILED=YES -co RESAMPLING=AVERAGE -co COMPRESS=LZW -co PREDICTOR=2` Ok I think maybe mroe straightforward to use this command

You could do it via rasterio [or python gdal api] if so inclined. e.g. https://github.com/OpenTopography/Jupyter/blob/main/OT_01_BulkAccessCOGs.ipynb
