### ISSUE TITLE
Incorrect transformation for southern hemisphere latitudes

### ISSUE THREAD

**Issue by Instatarama** [corteva/rioxarray#428]
I'm having trouble with the generated affine transformation. Rioxarray appears to be setting the top of the bounds as the last entry in the latitude dimension array. I understand the logic of this approach but it seems that with my data it creates incorrect affine transformations. It is setting the top lat as -44 where it should be -10, which means the resulting affine matrix is flipped. 

My data is in xarray format and the latitude data is sorted from south to north, making it tricky for rioxarray's bounds method. But would it be feasible to suggest that the bounds method in rioxarray would return a top coordinate as the closest latitude to the equator for southern hemisphere coordinates (lat<0)? 

Another issue outlined below is that when trying to write the corrected transform to the dataset using write_transform it makes no changes. 

```
west, north, east, south = aus.rio.bounds() # this has been deliberately modified to 
days, height, width = aus['CH4_column_volume_mixing_ratio_dry_air_destriped'].shape

tform = rasterio.transform.from_bounds(west, south, east, north, width, height)
print(tform)
```
| 0.02, 0.00, 110.60|
| 0.00,-0.02,-10.24|
| 0.00, 0.00, 1.00|

```
aus.rio.write_transform(transform=tform, inplace=True)
aus.rio.transform()
```
Affine(0.020000000000000004, 0.0, 110.60000000000001,
       0.0, -0.019999999999999993, -44.98)

#### Expected Output
An affine matrix like this one
| 0.02, 0.00, 110.60|
| 0.00,-0.02,-10.24|
| 0.00, 0.00, 1.00|

#### Environment Information
# Name                    Version                   Build  Channel
gdal                      3.3.2            py39h218ed2d_4    conda-forge
python                    3.9.7           hb7a2778_3_cpython    conda-forge
rasterio                  1.2.9            py39hb37810a_2    conda-forge
rioxarray                 0.7.1              pyhd8ed1ab_0    conda-forge
xarray                    0.19.0             pyhd8ed1ab_1    conda-forge

platform 'Linux-5.11.0-38-generic-x86_64-with-glibc2.33'

#### Installation method
 - conda

**Comment by snowman2** [comment]
Have you exported the data to a raster and loaded into QGIS to see what it looks like?

Are you able to provide the input data?

**Comment by Instatarama** [comment]
Thanks for responding so quickly,

I can see that the data seems to be accurately related to the latitudes but
it's still upside down, in that the affine has a north lat of -44 when it
should be -10.

This is after I reload the resulting COG raster file in Rasterio.

I've put an example file and the resulting raster in this drive folder.
https://drive.google.com/drive/folders/18SCIFS1cSVhL3KkyGrZFcy2LJEicUAjQ?usp=sharing

I know it's an easy fix to plot it correctly but this still seems like a
bug to me as the bounds return a latitude for top/north that is actually
the southmost latitude.

Thanks for looking into this.
D

**Comment by Instatarama** [comment]
I checked by using a different affine transformation (-10 as north) and producing a COG with Rasterio it is very wrong, so perhaps I was confidently incorrect on this. Anyway thanks for taking the time. Rioxarray is a great time-saver. 

D

**Comment by snowman2** [comment]
I ran this:
```python
rds = xarray.open_dataset("CH4_AUS_2020-01-01_V1.nc")
rds.squeeze().rio.to_raster("CH4_AUS_2020-01-01_V1.tif")
```
This is what the tiff output looks like for `surface_meridional_wind_velocity`:
![image](https://user-images.githubusercontent.com/8699967/139692417-71715c8c-5487-4049-bfde-c1914b841ed4.png)

This is what the `nc` output looks like for `surface_meridional_wind_velocity`:
![image](https://user-images.githubusercontent.com/8699967/139692154-ecb18729-eef8-429e-8a48-c30811b7e66d.png)

Based on that, I think `rioxarray` is handling the transform properly for your data.

**Comment by Instatarama** [comment]
OK, fair enough. Yes when I render my data through a tile server it also seems to be correct. It's a bit strange though that the bounds are placing the latitude -10 at the "bottom" though. 
![image](https://user-images.githubusercontent.com/54163162/139753827-866bd38a-01e0-403f-86c4-3ab77f89354c.png)
