### ISSUE TITLE
Clipping raster exactly to the extent of shapefile using rioxarray

### ISSUE THREAD

**Issue by rrsc1234** [corteva/rioxarray#441]
Hi. I have used the following code to clip the raster using shapefile (which should give resulting a raster of 512 pixels x 512 pixels):

```
from shapely.geometry import mapping
from shapely.wkt import loads
import rioxarray
import geopandas as gpd

gdf = gpd.read_file(r'D:\test_utm44.shp')
gdf_geom = str(gdf.geometry[0])
geom = mapping(loads(gdf_geom))

rds = rioxarray.open_rasterio(r'C:\Users\user\L8\Jan_144_45\LC08_L1TP_144045_B3.TIF', masked=True)
masked = rds.rio.clip([geom])
print(masked.shape)
```
The above code results in (3, 513, 513).

But when I am using gdalwarp to crop raster using shapefile then it results in a raster having shape (3, 512, 512).

```
import subprocess
inraster = r'C:\Users\user\L8\Jan_144_45\LC08_L1TP_144045_B3.TIF'
inshape = r'D:\test_utm44.shp'
outraster = r'F:\Data\data1.tif' 
subprocess.call(['gdalwarp', inraster, outraster, '-cutline', inshape, '-crop_to_cutline'])  
```

Can someone please let me know what could be the issue resulting in difference in shape of the output masked raster created by using rioxarray and gdal.

**Comment by snowman2** [comment]
You could try the [from_disk](https://corteva.github.io/rioxarray/stable/examples/clip_geom.html#Clipping-larger-rasters) option as it uses a different mechanism to clip.
```python
rds = rioxarray.open_rasterio(r'C:\Users\user\L8\Jan_144_45\LC08_L1TP_144045_B3.TIF', masked=True).rio.clip([geom], from_disk=True)
```

**Comment by rrsc1234** [comment]
> You could try the [from_disk](https://corteva.github.io/rioxarray/stable/examples/clip_geom.html#Clipping-larger-rasters) option as it uses a different mechanism to clip.
> 
> ```python
> rds = rioxarray.open_rasterio(r'C:\Users\user\L8\Jan_144_45\LC08_L1TP_144045_B3.TIF', masked=True).rio.clip([geom], from_disk=True)
> ```

I had tried this option "from_disk = True". But still the result is same.

**Comment by rrsc1234** [comment]
> rioxarray uses `rasterio` under the hood. Can you try this example? https://rasterio.readthedocs.io/en/latest/topics/masking-by-shapefile.html

Actually before trying for rioxarray I had tried rasterio after refering to the link which you had shared but the result is same which I am getting using rioxarray.

**Comment by snowman2** [comment]
In that case, I think this is a question for `rasterio`: https://github.com/rasterio/rasterio/

**Comment by rrsc1234** [comment]
> In that case, I think this is a question for `rasterio`: https://github.com/rasterio/rasterio/

Ok then I will open the issue in the link you have mentioned.
