### ISSUE TITLE
Preventing `spatial_ref = 0` in plot title

### ISSUE THREAD

**Issue by dshean** [corteva/rioxarray#443]
I'm wondering if there is a simple way to disable to default plot functionality from including the `spatial_ref = 0` in the plot title.  Didn't find anything in doc or issues, and all of the doc examples have this issue.  Seems like using the DataArray name (if set) or allowing the user to override with a string passed to a `title` keyword could work.  Can work around by adding a `xda.drop('spatial_ref').plot()` but seems like it should be default.  Thanks!

**Comment by snowman2** [comment]
Plotting is handled by xarray, so I think this question likely fits better here: https://github.com/pydata/xarray/discussions/categories/q-a

**Comment by dshean** [comment]
OK, I understand that plotting is handled by xarray.  But since the `spatial_ref` coordinate is added by rioxarray upon opening a raster dataset, it seems like rioxarray should be responsible for handling prior to plotting with xarray.  As far as I understand, if available, xarray will use additional coordinates in the Dataset for the title (like month=1) when creating a plot using the (x,y) coordinates.
Perhaps there is a simple, safe way to wrap the xarray plot call within rioxarray to drop `spatial_ref` coordinate?

**Comment by snowman2** [comment]
Your logic makes sense for why you would want to have that handled by rioxarray. However, rioxarray currently doesn't have any plotting support and it likely will be unmaintained if it is added. So, adding what you propose probably isn't the best long term solution. Asking the xarray developers will likely help you find the best solution to your question as they are more familiar with plotting.

**Comment by snowman2** [comment]
If someone wanted to create a plotting python library that handles plotting rasters, there may be interest by other developers. See #208

**Comment by snowman2** [comment]
Closing for preference for documentation on how to handle it (see #208).
