### ISSUE TITLE
Add method to merge xarrays geospatially

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#46]

**Comment by rbavery** [comment]
+1 to this, and thanks for releasing this project! I am working with lists of rioxarray Data Arrays, all in the same projection, but different extents and partial overlap of cells (cell boundaries do not align perfectly because the sensor has a non uniform orbit). But I can't figure out how to merge them, the merges end up taking a long time and as expected the resulting arrays are huge due to the many unique coordinates that are very close to each other across different images acquired on different orbits. 

So I have two problems, one is snapping multiple geospatial rasters onto a single basis raster (like ArcGIS's Snap to Grid) and the other is merging these geospatial rasters that have different extents and missing data.

Below is an example of two rasters I'm working with. Any suggestions on aligning rasters with overlapping coordinates that do not quite match each other would be appreciated!

```python
<xarray.DataArray 'ECO3ETPTJPL.001_EVAPOTRANSPIRATION_PT_JPL_ETdaily_doy2018222180613_aid0001.tif' (y: 6324, x: 3345)>
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
Coordinates:
    band         int64 1
  * y            (y) float64 47.0 47.0 47.0 47.0 ... 43.02 43.02 43.02 43.02
  * x            (x) float64 4.0 4.0 4.001 4.002 ... 6.104 6.105 6.105 6.106
    date         datetime64[ns] 2018-08-10T18:06:13
    spatial_ref  int64 0
Attributes:
    transform:      (0.000629777416967, 0.0, 3.9994728340447265, 0.0, -0.0006...
    scales:         (1.0,)
    offsets:        (0.0,)
    add_offset:     0
    AREA_OR_POINT:  Area
    build_id:       0503
    orbit_number:   00543
    scale_factor:   1
    scene_id:       021
    units:          W/m^2
    _FillValue:     -9999999999999.0
    grid_mapping:   spatial_ref

<xarray.DataArray 'ECO3ETPTJPL.001_EVAPOTRANSPIRATION_PT_JPL_ETdaily_doy2018250064210_aid0001.tif' (y: 2711, x: 3236)>
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
Coordinates:
    band         int64 1
  * y            (y) float64 47.0 47.0 47.0 47.0 47.0 ... 45.3 45.29 45.29 45.29
  * x            (x) float64 4.0 4.001 4.001 4.002 ... 6.035 6.036 6.037 6.037
    date         datetime64[ns] 2018-09-07T06:42:10
    spatial_ref  int64 0
Attributes:
    transform:      (0.0006297774169669998, 0.0, 3.9996370876977334, 0.0, -0....
    scales:         (1.0,)
    offsets:        (0.0,)
    add_offset:     0
    AREA_OR_POINT:  Area
    build_id:       0503
    orbit_number:   00971
    scale_factor:   1
    scene_id:       013
    units:          W/m^2
    _FillValue:     -9999999999999.0
    grid_mapping:   spatial_ref
```

![Selection_016](https://user-images.githubusercontent.com/22258697/68190167-c1369080-ff61-11e9-9606-1e5bc03728c8.png)

**Comment by snowman2** [comment]
Welcome @rbavery! Hopefully this will help:

> snapping multiple geospatial rasters onto a single basis raster

I would recommend `rio.reproject_match`. An example of what you want to do is in the docs [here](https://corteva.github.io/rioxarray/html/examples/reproject_match.html).

> merging these geospatial rasters that have different extents and missing data.

Until this is added to `rioxarray`, you could try `rasterio.merge.merge` [docs](https://rasterio.readthedocs.io/en/stable/api/rasterio.merge.html#rasterio.merge.merge).

> the merges end up taking a long time and as expected the resulting arrays are huge due to the many unique coordinates that are very close to each other across different images acquired on different orbits.

I would recommend only keeping the first one as a DataArray and then storing the rest as tuples without coordinates to reduce the size. You can store all of the data in a dictionary and then re-create a dataset:

```python
data_dict = {}
data_dict[var_name] = (
    ("y", "x"),
    band_data,
    band_attributes,
)
```

**Comment by rbavery** [comment]
Thanks a bunch! Didn't realize reproject_match was what I needed. With the use of geocube to rasterize my aoi I used that as the basis raster for `reproject_match` and was able to merge all my rasters with `xarray.concat(list_of_data_arrays, dim="date")`.

**Comment by snowman2** [comment]
Nice! Would you be willing to create a small example of what you did and add it to the docs? Definitely don't have to, but sounds like a useful example for others to see.

**Comment by rbavery** [comment]
Yes, for sure. Should the example make the data downloadable or are the code and plot examples fine?  I'm working with ECOSTRESS scenes, each of which is about 152 Mb and ordering them through NASA's Appeears API takes a a few days, not super feasible in an example.

**Comment by snowman2** [comment]
Great! If you are able to get a small example with 2 scenes where the URL is downloadable, that would be the best scenario so we can update the example in the future. But, if that is not possible, just code and images are the next best thing.

If you use jupyter notebooks, then adding the notebook would be next step after getting it setup. Examples are here: https://github.com/corteva/rioxarray/tree/master/sphinx/examples. Once added, just update `examples.rst` in the same directory with the name of the notebook.

Feel free to ask questions as you go along.
