### ISSUE TITLE
BUG: empty gcps with older versions of rasterio (1.2.1)

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#464]
See: https://github.com/corteva/rioxarray/actions/runs/1819395031

```
E           TypeError: Invalid value for attr 'gcps': {'type': 'FeatureCollection', 'features': []}. For serialization to netCDF files, its value must be of one of the following types: str, Number, ndarray, number, list, tuple
```

**Comment by mraspaud** [comment]
@snowman2 I'm having a look

**Comment by snowman2** [comment]
My guess is that it has something to do with the check here: https://github.com/corteva/rioxarray/blob/abb66c203ab9feb16c60a908c4eb58cfa75d26d2/rioxarray/_io.py#L883

**Comment by mraspaud** [comment]
Yes, that's what I'm thinking too... Trying to get rasterio 1.2.1 installed now
