### ISSUE TITLE
How to get epsg or proj crs?

### ISSUE THREAD

**Issue by rsignell-usgs** [corteva/rioxarray#49]
I'm trying to use `rioxarray.open_rasterio` to create an xarray dataarray from a COG and then use `hvplot` to visualize it, which takes a Cartopy crs argument.

This is a bit embarrassing but I can't figure out how to obtain a crs proj or epsg code from `rioxarray.open_rasterio`.

If I use `xarray.open_rasterio` I have `.crs`, which gives me the proj or epsg code, but with `rioxarray.open_rasterio` I see `spatial_ref`, which contains `wkt`. 

Example:
```python
# from https://openaerialmap.org/
cog_url = (
    "https://oin-hotosm.s3.amazonaws.com/"
    "5d7dad0becaf880008a9bc88/0/5d7dad0becaf880008a9bc89.tif"
)
import xarray as xr
xr.open_rasterio(cog_url).crs
```
yields:
```
'+init=epsg:3857'
```
But rioxarray:
```python
import rioxarray as rx
rioxarray.open_rasterio(cog_url).spatial_ref
```
yields:
```
<xarray.DataArray 'spatial_ref' ()>
array(0)
Coordinates:
    spatial_ref  int64 0
Attributes:
    spatial_ref:  PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WG...
    crs_wkt:      PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WG...
```
I think I'm definitely missing something here.  😕

**Comment by snowman2** [comment]
I think what you want is: 

```python
xds.rio.crs.to_proj4()
```
https://corteva.github.io/rioxarray/html/examples/crs_management.html

**Comment by snowman2** [comment]
The documentation is a work in progress. If you have any recommendations, it would be helpful to hear another perspective.

**Comment by snowman2** [comment]
Closing as I believe your issue has been resolved. If not, feel free to reopen or just continue to ask questions.

**Comment by rsignell-usgs** [comment]
Yes, @snowman2, that indeed solved my problem!  I don't know what documentation I was looking at, because I could have sworn I searched on `crs` and didn't see all that useful information.  Thanks for being patient and your polite response to my question.   I'll try to be more careful next time.

**Comment by snowman2** [comment]
Glad to hear it worked well for you! No worries - I miss things quite a bit myself :)
