### ISSUE TITLE
ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

### ISSUE THREAD

**Issue by cheukhin1024** [corteva/rioxarray#493]
I tried "pip install rioxarray" in Visual Studio Code, but there is the following error:
 

```
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp552tnlc8'
       cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-ald_jmvb\rasterio_978074d223d44fc5a3f6748cafeacc87
  Complete output (2 lines):
  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

```

After trying to install it, I run the code. 

```
import pystac
import planetary_computer
import rioxarray

item_url = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/naip/items/fl_m_2808060_sw_17_060_20191215_20200114"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets 
asset_href = signed_item.assets["image"].href
ds = rioxarray.open_rasterio(asset_href)
ds
```

However, there is an error:

```
Exception has occurred: ModuleNotFoundError
No module named 'rioxarray'
```

**Comment by snowman2** [comment]
rasterio handles the interface to GDAL. I recommend reading their docs.

See: https://github.com/rasterio/rasterio

**Comment by cheukhin1024** [comment]
> rasterio handles the interface to GDAL. I recommend reading their docs.
> 
> See: https://github.com/rasterio/rasterio


Are you suggesting using their lib? (I am a new beginner at analyzing times series image data, eg satellite images)

**Comment by snowman2** [comment]
`rasterio` is a dependency of `rioxarray`. The installation issues you are running into are because you are having troubles installing `rasterio`. Once you have `rasterio` installed in your python environment, you should be able to install `rioxarray`.

**Comment by cheukhin1024** [comment]
> `rasterio` is a dependency of `rioxarray`. The installation issues you are running into are because you are having troubles installing `rasterio`. Once you have `rasterio` installed in your python environment, you should be able to install `rioxarray`.

 Okay

**Comment by snowman2** [comment]
I believe this issue has been resolved. If it hasn't, feel free to ask further questions.
