### ISSUE TITLE
DOC: Default value for `inplace` argument of `RasterArray.set_nodata` is inconsistent with its docstring.

### ISSUE THREAD

**Issue by apiwat-chantawibul** [corteva/rioxarray#508]
https://github.com/corteva/rioxarray/blob/64cc0943973d6a231f93ed76682a3b0571a2a70d/rioxarray/raster_array.py#L247-L265

**Comment by snowman2** [comment]
The docstring should say default=True. A PR with a fix is welcome.

**Comment by apiwat-chantawibul** [comment]
#509 sure. That was my first pull request ever; please advise.

**Comment by snowman2** [comment]
> That was my first pull request ever; please advise.

Looks great, thanks!
