### ISSUE TITLE
Why not use the actual Affine object for xarray.DataArray.transform instead of tuple

### ISSUE THREAD

**Issue by pmallas** [corteva/rioxarray#53]
I am just curious if you ever thought about using the Affine object as the transform value rather than a tuple of the coefficients?

**Comment by snowman2** [comment]
First off, welcome!

If I am correct, I assume that you are referring to the `transform` attribute that exists when loading using `rioxarray.open_rasterio`. 
```python
>>> import rioxarray
>>> rds = rioxarray.open_rasterio("rad.tif")
>>> rds
<xarray.DataArray (band: 1, y: 6000, x: 10000)>
[60000000 values with dtype=float64]
Coordinates:
  * band         (band) int64 1
  * y            (y) float64 1.583e+06 1.584e+06 ... 4.588e+06 4.589e+06
  * x            (x) float64 -2.505e+06 -2.504e+06 ... 2.504e+06 2.505e+06
    spatial_ref  int64 0
Attributes:
    transform:     (501.0043288718852, 0.0, -2505021.4937798134, 0.0, 501.004...
    _FillValue:    4095.0
    scales:        (1.0,)
    offsets:       (0.0,)
    grid_mapping:  spatial_ref
>>> rds.transform
(501.0043288718852, 0.0, -2505021.4937798134, 0.0, 501.00432887188526, 1583173.639055641)
```
The reason it is a tuple is because a tuple is serializable when writing to a netcdf and and the `Affine` python object is not. However, the `Affine` object is available via the `rio` accessor with the `transform()` method:
```python
>>> rds.rio.
rds.rio.bounds(            rds.rio.set_nodata(
rds.rio.clip(              rds.rio.set_spatial_dims(
rds.rio.clip_box(          rds.rio.shape
rds.rio.crs                rds.rio.slice_xy(
rds.rio.encoded_nodata     rds.rio.to_raster(
rds.rio.height             rds.rio.transform(
rds.rio.interpolate_na(    rds.rio.transform_bounds(
rds.rio.nodata             rds.rio.update_attrs(
rds.rio.reproject(         rds.rio.width
rds.rio.reproject_match(   rds.rio.write_crs(
rds.rio.resolution(        rds.rio.write_nodata(
rds.rio.set_attrs(         rds.rio.x_dim
rds.rio.set_crs(           rds.rio.y_dim
>>> rds.rio.transform()
Affine(501.0043288718852, 0.0, -2505021.4937798134,
       0.0, 501.00432887188526, 1583173.639055641)
```
Hopefully this helps.

**Comment by pmallas** [comment]
Thanks.  This makes sense - I just noticed that the Affine object was used in some cases from transform and not others.

**Comment by snowman2** [comment]
> I just noticed that the Affine object was used in some cases for transform and not others.

What cases did you notice where the affine object was not used?

**Comment by pmallas** [comment]
Sorry, I guess I was not clear.  I just meant that the transform ( the attribute) is a tuple and transform (accessor function) returns an Affine object. This seemed inconsistent to me at first, but you have a reason for doing things this way.

**Comment by snowman2** [comment]
Okay, thanks for the clarification 👍
