### ISSUE TITLE
RuntimeWarning when I try to plot a raster

### ISSUE THREAD

**Issue by MaxDragonheart** [corteva/rioxarray#531]
I'm not sure if It is a bug or my mistake.

I'm using JupyterNotebook to analyze some GIS data. I need to clip a raster and plot the result but I've a strange problem. Folder with data is [here](https://github.com/MaxDragonheart/PyGIS-Blog/tree/post_%2312/sample_data/photovoltaic_potential_analysis); the raster size is 1MB.

I'm be able to plot the source raster without problem:
```
import geopandas as gpd
import rioxarray as rxr
from xarray.plot import imshow

vector = gpd.read_file(buildings)
raster = rxr.open_rasterio(dsm).squeeze()

fig, ax = plt.subplots(figsize=(10, 10))

imshow(
    raster,
    cmap='Blues',
    ax=ax,
)
plt.show()
```
[![enter image description here][1]][1]

I clip the raster with a GeoDataframe with a hundred polygons.
```
raster_clipped = raster.rio.clip(
    geometries=vector.geometry, crs=raster.rio.crs, all_touched=True, drop=True
)
```
Below the output:
[![enter image description here][2]][2]

With the code below I save the output so I can see it also with QGIS:
```
raster_clipped.rio.to_raster('clip.tif', driver="GTiff")
```
[![enter image description here][3]][3]
The problem comes when I try to plot the clipped raster inside a JupyterNotebook:
```
fig, ax = plt.subplots(figsize=(10, 10))

imshow(
    raster_clipped,
    cmap='Blues',
    ax=ax,
)
plt.show()
```
I see the image below:
[![enter image description here][4]][4]
And this error:

> /home/max/.cache/pypoetry/virtualenvs/pygis_blog-Mlm5bQxV-py3.8/lib/python3.8/site-packages/matplotlib/image.py:480: RuntimeWarning: overflow encountered in subtract
  vrange -= a_min

It seems I can see only the nodata values:
```
fig, ax = plt.subplots(figsize=(10, 10))
raster_clipped.plot.hist(color="blue", bins=10)
ax.set_title("Highs distribution")
plt.show()
```
[![enter image description here][5]][5]

  [1]: https://i.stack.imgur.com/DFdG7.png
  [2]: https://i.stack.imgur.com/sbGOz.png
  [3]: https://i.stack.imgur.com/B4SBi.png
  [4]: https://i.stack.imgur.com/k3YWN.png
  [5]: https://i.stack.imgur.com/iXYGV.png

**Comment by snowman2** [comment]
Option 1: Opening in masked mode

```python
rioxarray.open_rasterio(dsm, masked=True)
```

Option 2: plot with robust=True

https://docs.xarray.dev/en/stable/user-guide/plotting.html#robust

**Comment by MaxDragonheart** [comment]
Thank you @snowman2 ! 
I've used the first option :smile:
