### ISSUE TITLE
Transform assignation is different?

### ISSUE THREAD

**Issue by RichardScottOZ** [corteva/rioxarray#546]
#### Code Sample, a copy-pastable example if possible

Generally I fix this with rasterio, thought I would have a look here:-

```python
# Your code here
dtm = rioxarray.open_rasterio(r'F:\Depth Modelling\Features008_200\dtm_SA_200_3107.tif')
dtm.rio.transform()

Affine(200.0, 0.0, 339300.0,
       0.0, -200.0, 2732900.0)

dtb= rioxarray.open_rasterio(r'F:\Depth Modelling\dtb.tif')
dtb.rio.transform()

Affine(200.0, 0.0, 339300.0,
       0.0, 200.0, 1209900.0)

newtransform = dtm.rio.transform()

dtb.rio.write_transform(newtransform,inplace=True)
dtb.rio.transform()

Affine(200.0, 0.0, 339300.0,
       0.0, -200.0, 1210100.0)

```
#### Problem description

New transform is not quite right?.

#### Expected Output
```python
Affine(200.0, 0.0, 339300.0,
       0.0, -200.0, 2732900.0)
```

presumably this is some affine handling would have to do differently - as updating rasterio metadata directly just assign a new transform tuple to the dictionary

#### Environment Information

 - `python -c "import rioxarray; rioxarray.show_versions()"`
rioxarray (0.9.1) deps:
  rasterio: 1.2.3
    xarray: 0.18.2
      GDAL: 3.2.1

#### Installation method
 - conda, pypi, from source, etc...
conda

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list | grep -E "rasterio|xarray|gdal"
![image](https://user-images.githubusercontent.com/72196131/178165021-c61ae467-abf4-4e4a-82a9-a3b7d349d6b1.png)

```
</details>

**Comment by RichardScottOZ** [comment]
e.g. flipping data, bounds, affine elements, access to/updating etc.

**Comment by snowman2** [comment]
The different value in the transform has to do with the coordinates loaded in from the original raster. Since rasters can be sliced and subsets extracted from the raster, the value of the transform is calculated from the ooordinates and not from the transform alone.

If you want the transform to be the same in the second raster, you also have to copy over the coordinates of the original raster.

**Comment by RichardScottOZ** [comment]
Thanks Alan, figured it was something along those lines - stuck in a meeting before I could do some more tests.

**Comment by RichardScottOZ** [comment]
![image](https://user-images.githubusercontent.com/72196131/178179349-881edf01-29a5-4837-9dff-05f11ee8f40c.png)
