### ISSUE TITLE
Add boolean keyword trans_recalc to  to_raster() to turn transform recalculation on/off

### ISSUE THREAD

**Issue by pmallas** [corteva/rioxarray#55]
I am wondering if the maintainers here would consider allowing the addition of a keyword that would allow user to turn off the recalculation of the transform in to_raster(). Currently, the tranform is always recalculated:

with rasterio.open(
         ....
          transform=self.transform(recalc=True)
           ...) 
 
I would propose something like:

def to_raster(
    …
    trans_recalc = True
    …)

and 

with rasterio.open(
         ....
          transform=self.transform(recalc=trans_recalc)
           ...) 

Any objections?

**Comment by snowman2** [comment]
Sounds reasonable. How about `recalc_transform` defaulting to True?

**Comment by pmallas** [comment]
Ok, I think I proposed the change and did the edit correctly.  I am not terribly familiar with how to make changes on GitHub, so if I missed something or skipped a step, I apologize.

**Comment by pmallas** [comment]
Ok, I probably screwed it up.  I think I proposed the change on the master.  Rookie mistake - I will fork and edit.

**Comment by snowman2** [comment]
No, you have it perfect.
