### ISSUE TITLE
Set xarray "preferred_chunks" based on rasterio.block_shapes

### ISSUE THREAD

**Issue by scottyhq** [corteva/rioxarray#567]
It could be nice to take advantage of known raster tiling (rasterio`.block_shapes`) to assign dask chunks when opening tiled datasets. It seems straightforward to implement with xarray's [backend preferred chunk sizes](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html#preferred-chunk-sizes). 

Setting this could also avoid common errors with exploding task graphs when users rely on defaults (chunks=True) or reading way more data than necessary (chunks={}).

According to xarray docs for [open_dataset/open_dataarray](https://docs.xarray.dev/en/v2022.06.0/generated/xarray.open_dataset.html), "chunks={} loads the dataset with dask using engine preferred chunks if exposed by the backend, otherwise with a single chunk for all arrays. chunks='auto' will use dask auto chunking".  Below is an example with some public data (18287x18460 with 256x256 tiling):

```python
import xarray as xr
import rasterio
url = 'https://capella-open-data.s3.amazonaws.com/data/2022/4/21/CAPELLA_C06_SP_GEO_HH_20220421064500_20220421064519/CAPELLA_C06_SP_GEO_HH_20220421064500_20220421064519_preview.tif'

with rasterio.open(url) as src:
    print(src.block_shapes) # [(256, 256)]

# This is okay, but not optimal due to misalignment with 256 block_shapes
da = xr.open_dataarray(url, chunks='auto', engine='rasterio')
# da.chunksizes 
# Frozen({'band': (1,), 'y': (9087, 9087, 113), 'x': (3692, 3692, 3692, 3692, 3692)})
```
<img width="485" alt="Screen Shot 2022-08-24 at 5 20 59 PM" src="https://user-images.githubusercontent.com/3924836/186546662-033ead10-117d-4bb8-8d42-210954bb6dc5.png">

```python
# Warning! This is the same as chunks=1, which explodes the number of tasks
da = xr.open_dataarray(url, chunks=True, engine='rasterio')
```
<img width="518" alt="Screen Shot 2022-08-24 at 5 21 44 PM" src="https://user-images.githubusercontent.com/3924836/186546681-ae424949-345d-4628-bc18-60e43ee05312.png">

```python
# Warning! You'll be reading all pixel values even if you just want 1
xr.open_dataarray(url, chunks={}, engine='rasterio')
```
<img width="495" alt="Screen Shot 2022-08-24 at 5 21 25 PM" src="https://user-images.githubusercontent.com/3924836/186546718-a23fc90f-8322-4a38-839f-9aba77e999b2.png">

There are many considerations for *optimal* chunks (see [dask blog](https://blog.dask.org/2021/11/02/choosing-dask-chunk-sizes)), but a good default size could be determined by ~100Mb and a multiple of 256x256?

**Comment by snowman2** [comment]
Mind moving this to #253 ?

**Comment by scottyhq** [comment]
> Mind moving this to https://github.com/corteva/rioxarray/issues/253 ?
🤦 sorry i overlooked that! Should I just copy/paste and close this one?

**Comment by snowman2** [comment]
> sorry i overlooked that! Should I just copy/paste and close this one?

No worries. I overlook things all the time :smile:. Yes, please.
