### ISSUE TITLE
import error caused by old numpy version

### ISSUE THREAD

**Issue by ghiggi** [corteva/rioxarray#587]
This error appears when importing rioxarray and is related to the numpy version.

I think you should constrain numpy to be > 1.21.6 (which solves the problem).

With numpy 1.21.3, importing rioxarray raise the following ImportError

`ImportError: cannot import name 'NDArray' from 'numpy.typing' (/home/ghiggi/.conda/envs/satpy39/lib/python3.9/site-packages/numpy/typing/__init__.py)`

#### Environment Information
 - rioxarray version: 0.12.2
-  numpy: 1.21.3

**Comment by snowman2** [comment]
Interesting, numpy says it was added in 1.21:  https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray

**Comment by itcarroll** [comment]
The latest build of rioxarray on conda forge (rioxarray-0.13.3-pyhd8ed1ab_1) now depends on numpy>1.21. I just installed numpy 1.21.0 and am able to import rioxarray without error. Is this still occurring for you @ghiggi?

@snowman2 Want a PR to add the dependency to `setup.cfg` for pip users as well?

**Comment by snowman2** [comment]
Sure, a PR is welcome 👍
