### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by huard** [corteva/rioxarray#61]
#### Code Sample, a copy-pastable example if possible

```python
import rioxarray
```
#### Problem description

Import seems to fail on Python 3.5 with version 0.0.15. 
Python 3.5 does not seem to be part of the Travics-CI suite. 

```
>>> import rioxarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.conda/envs/xclim3.5/lib/python3.5/site-packages/rioxarray/__init__.py", line 8, in <module>
    import rioxarray.rioxarray  # noqa
  File "/home/david/.conda/envs/xclim3.5/lib/python3.5/site-packages/rioxarray/rioxarray.py", line 1104
    **profile_kwargs,
                    ^
SyntaxError: invalid syntax
>>> 

```

#### Output of ``rioxarray --version``

<details>
rioxarray: command not found
</details>

**Comment by snowman2** [comment]
`xarray` has dropped support for python 3.5 [here](https://github.com/pydata/xarray/pull/3358). As such, I don't think we will be able to support it moving forward.

**Comment by huard** [comment]
Ok. Then I suggest updating `setup.py` to reflect that. Thanks for the quick response !

**Comment by snowman2** [comment]
> I suggest updating setup.py to reflect that.

Agreed! Definitely needs to happen for clarity purposes.

**Comment by snowman2** [comment]
https://github.com/corteva/rioxarray/commit/09c3d789a0643d63c1421de6182150e3050edea9
