### ISSUE TITLE
Allow user assigned CRS in open_rasterio

### ISSUE THREAD

**Issue by peterm790** [corteva/rioxarray#646]
I am looking to open [MODIS level 2](https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/MOD11_L2#overview) hdf data, sourced from [here](https://search.earthdata.nasa.gov/search). I've also uploaded a sample file to s3://peterm790/MOD11_L2.A2023060.2040.061.2023061090549.hdf for convenience. 

My understanding is after https://github.com/corteva/rioxarray/pull/62 it should be possible to open these files by simply calling:

```
rds = rioxarray.open_rasterio('/path/to/MOD11_L2.A2023060.2040.061.2023061090549.hdf')
```

This however returns the following error:

```
MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.
```

a gist with the full error message: https://gist.github.com/peterm790/6a3dd266def15b2a5bfa04a3c63825a6

My understanding is the present API does not allow for manually setting the CRS when opening a file. Is there a way around this? if not does it make sense to allow for this? Or should it be possible to open the file without setting the CRS? 

I have set up a branch: https://github.com/corteva/rioxarray/compare/master...peterm790:rioxarray:assign_crs which allows the CRS to be set manually with an `assign_crs` argument in `open_rasterio`such that:

```
rds = rioxarray.open_rasterio('/path/to/MOD11_L2.A2023060.2040.061.2023061090549.hdf', assign_crs = "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs")
```

successfully opens the files. here's a gist of this https://gist.github.com/peterm790/f06d846e518c2ced7741afcda5365aed

Please do let me know if there is another method for opening these MODIS L2 files that I have missed? Or if a PR allowing the above change would make sense.

**Comment by snowman2** [comment]
What is the output of `rioxarray.show_versions()`?

**Comment by peterm790** [comment]
rioxarray.show_versions():
```
rioxarray (0.13.3) deps:
  rasterio: 1.3.4
    xarray: 2023.1.0
      GDAL: 3.6.2
      GEOS: 3.11.1
      PROJ: 9.1.0
 PROJ DATA: /share/apps/anaconda3-2022.05/envs/pangeo/share/proj
 GDAL DATA: None

Other python deps:
     scipy: 1.10.0
    pyproj: 3.4.1

System:
    python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
executable: /share/apps/anaconda3-2022.05/envs/pangeo/bin/python
   machine: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.17
```

**Comment by snowman2** [comment]
This is interesting - it seems to think there are GCPS, but no CRS is found:
```python
if has_gcps:
    result.rio.write_gcps(*riods.gcps, inplace=True)
```

**Comment by snowman2** [comment]
```python
with rasterio.open("MOD11_L2.A2023060.2335.061.2023061090119.hdf") as rds:
    for subdataset in rds.subdatasets:
        with rasterio.open(subdataset) as subrds:
            print(subdataset)
            print(subrds.gcps[0][0], subrds.gcps[1])
```
```
HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:LST
GroundControlPoint(row=2.5, col=2.5, x=115.89305877685547, y=-62.6209831237793, z=0.0, id='', info='') None
HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:QC
GroundControlPoint(row=2.5, col=2.5, x=115.89305877685547, y=-62.6209831237793, z=0.0, id='', info='') None
HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:Error_LST
GroundControlPoint(row=2.5, col=2.5, x=115.89305877685547, y=-62.6209831237793, z=0.0, id='', info='') None
HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:Emis_31
GroundControlPoint(row=2.5, col=2.5, x=115.89305877685547, y=-62.6209831237793, z=0.0, id='', info='') None
HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:Emis_32
GroundControlPoint(row=2.5, col=2.5, x=115.89305877685547, y=-62.6209831237793, z=0.0, id='', info='') None
HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:View_angle
GroundControlPoint(row=2.5, col=2.5, x=115.89305877685547, y=-62.6209831237793, z=0.0, id='', info='') None
HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:View_time
GroundControlPoint(row=2.5, col=2.5, x=115.89305877685547, y=-62.6209831237793, z=0.0, id='', info='') None
```

**Comment by snowman2** [comment]
Related: https://github.com/corteva/rioxarray/issues/339#issuecomment-853877629

**Comment by snowman2** [comment]
This returns nothing for the GCPS:
```python
from osgeo import gdal

ds = gdal.Open("HDF4_EOS:EOS_SWATH:MOD11_L2.A2023060.2335.061.2023061090119.hdf:MOD_Swath_LST:LST")

ds.GetGCPSpatialRef()
```
I am wondering if GDAL needs to be updated to handle that (https://github.com/OSGeo/gdal)? Or if it is an issue with how the files are generated?

**Comment by snowman2** [comment]
@peterm790, with the gist you added, there are no coordinates/transform. So, there isn't much you can do with the data and it can be misleading to have a CRS without the correct coordinates/transform/gcps. I am thinking it would likely be better to either address the issue with the data provider or with GDAL.

However, to allow reading the file, a PR with a change that skips writing the CRS if `gcp_crs` is None here would be welcome:
https://github.com/corteva/rioxarray/blob/33a1be6f1bc3e30cb6d8c1a002d04f439dfb510f/rioxarray/rioxarray.py#L1233-L1235

**Comment by peterm790** [comment]
So just to update this issue for anybody that may come here in the future. My understanding of the MOD11_L2 data was a bit floored, while it does contain ground control points it is not a geo-referenced product and so attempting to re project does not make sense. Instead the level 3 MOD11A1 product should be used. This document was useful to me: https://landweb.modaps.eosdis.nasa.gov/QA_WWW/forPage/user_guide/061/MOD11_C61_UsersGuide_revSudipta_revPete_Final.pdf 

Despite this I do think https://github.com/corteva/rioxarray/pull/648 which allows the data and gcps to be opened and viewed makes sense.
