### ISSUE TITLE
"'open_rasterio' is not exported from module 'rioxarray'" error reported by Pylance linting

### ISSUE THREAD

**Issue by dluks** [corteva/rioxarray#680]
I'm not so sure this is a bug as everything still technically functions fine so I'm including it in feature requests.

Pylance in VS Code (v1.80.0-insider (Universal)) throws a pyright [`reportPrivateImportUsage`](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportPrivateImportUsage) error when accessing `open_rasterio` from `rioxarray`.

For people who rely on `reportPrivateImportUsage` this is a bit annoying.

Steps to reproduce:

Use VS Code (Insider or regular) with Pylance and lint the following lines:
```python
import rioxarray

raster = "path/to/raster"
dataset = rioxarray.open_rasterio(raster)
```

**Comment by dluks** [comment]
I can do that, but it should be noted that this also occurs on the LTS version for Mac. I wonder if it has anything to do with how `rioxarray` is including or inheriting`xarray`'s `open_rasterio` method? For the record, pylance does not report the error for `xarray.open_rasterio()`.

**Comment by snowman2** [comment]
This is what the error is likely complaining about: https://github.com/corteva/rioxarray/blob/ec26269924f59c878679f137758071515ac72e7c/rioxarray/__init__.py#L7

However, I don't think that pylance should care about private import within the same package.

**Comment by Kirill888** [comment]
I believe this is due to missing `__all__`.
