### ISSUE TITLE
Document difference between `set_crs` and `write_crs`

### ISSUE THREAD

**Issue by ttencate** [corteva/rioxarray#743]
`set_crs`:

> Set the CRS value for the Dataset/DataArray without modifying the dataset/data array.

`write_crs`:

> Write the CRS to the dataset in a CF compliant manner.

The `input_crs` and `inplace` arguments are the same; the only difference in signature is that `write_crs` takes an optional `grid_mapping_name`.

In short, I'm confused :wink: 

Maybe consider `write_coordinate_system` in this issue as well.

**Comment by snowman2** [comment]
Looks like you found this: https://corteva.github.io/rioxarray/stable/getting_started/crs_management.html

`set_crs` is not recommended to use because the CRS doesn't persist.

**Comment by ttencate** [comment]
Good to know, thanks. Would be great if the docs noted this, and also explained what `set_crs` would be used for.

**Comment by snowman2** [comment]
Related #356
