### ISSUE TITLE
Rio array merge missing

### ISSUE THREAD

**Issue by sehHeiden** [corteva/rioxarray#759]
I want to merge arrays but the module is gone in 0.15.1

```python
import rioxarray

out = Rio array.merge.merge_arrays([rioxarray.open_rasterio(x) for x in inpath.iterdir()]) 
```
#### Problem description

AttributeError: module 'rioxarray' has no attribute 'merge'. 

#### Environment Information

rioxarray 0.15.1
pyhton 3.11.6
rasterio.1.3.9
xarray: 2024.1.1
gdal: 3.6.4
geos: 3.11.2
proj: 9.0.1

others
scipy 1.12.0
Pyproj 3.6.1

#### Installation method
 - with pip and pypi

Written on mobile phone, so may contain some typos.

**Comment by RichardScottOZ** [comment]
Missing the accessor?

**Comment by snowman2** [comment]
Try this:

```python
from rioxarray.merge import merge_arrays
```

**Comment by sehHeiden** [comment]
The later works.
