### ISSUE TITLE
Having dict-encoded GCPs leads to `to_netcdf` failing with a `TypeError`

### ISSUE THREAD

**Issue by cpegel** [corteva/rioxarray#778]
#### Code Sample

```python
import xarray as xr
import rioxarray
from rasterio.control import GroundControlPoint
from rasterio.crs import CRS

ds = xr.Dataset(dict(A=xr.DataArray([1.0])))

gcps = [GroundControlPoint(row=0, col=0, x=10, y=10, z=0, id='0', info='')]
crs = CRS.from_epsg(4326)

ds.rio.write_gcps(gcps, crs, inplace=True)

ds.to_netcdf("/path/to/dataset.nc")
# TypeError: Invalid value for attr 'gcps': {'type': 'FeatureCollection', 'features': [{'type': 'Feature', 'properties': {'id': '0', 'info': '', 'row': 0, 'col': 0}, 'geometry': {'type': 'Point', 'coordinates': [10, 10, 0]}}]}. For serialization to netCDF files, its value must be of one of the following types: str, Number, ndarray, number, list, tuple
```

#### Problem description

Since rioxarray currently encodes GCPs as a GeoJSON dict in the `spatial_ref` attribute `gcps`, a GCP referenced dataset can not be saved as NetCDF.

#### Expected Output

I would expect to be able to save a GCP referenced dataset as NetCDF. This could easily be fixed by calling `json.dumps` on the GeoJSON-dict and storing the resulting string in the `gcps` attribute instead (and calling `json.loads` before reading the GCPs in the accessor function `get_gcps`).

**Comment by snowman2** [comment]
Yes, it should be stored as a GeoJSON string. A PR with a fix is welcome.
