### ISSUE TITLE
why does `write_grid_mapping` check for spatial dims?

### ISSUE THREAD

**Issue by dcherian** [corteva/rioxarray#791]
#### Problem description

I am looking at the vector data cube example here that has a CRS: https://xvec.readthedocs.io/en/stable/io.html#pickle-joblib
<img width="813" alt="image" src="https://github.com/corteva/rioxarray/assets/2448579/cafbea57-37aa-4400-b667-ff9c90cb129d">

I used `cube.rio.set_crs(cube.xindexes["county"].crs)` which adds a `spatial_ref` variable but does not add the `grid_mapping` attribute on any of the data variables.

Looking at the code, I see that it skips adding this attribute if it doesn't know about the x,y dims.

https://github.com/corteva/rioxarray/blob/978ae3cd5d2e4aae9e1555d00f1b114c988e79e8/rioxarray/rioxarray.py#L428-L431

Why is this check here though? IIUC the data are associated with a CRS, and a polygon in this case, so there is no x,y here.

#### Expected Output

`grid_mapping` attribute is added.

**Comment by snowman2** [comment]
> Why is this check here though?

The `grid_mapping` should only be added to geospatial data variables. The check ensures that is the case.

> IIUC the data are associated with a CRS, and a polygon in this case, so there is no x,y here.

rioxarray is scoped to support raster data. It does not support vector data. [geoxarray](https://github.com/geoxarray/geoxarray/) may potentially be scoped to support both?

**Comment by snowman2** [comment]
> cube.rio.set_crs(cube.xindexes["county"].crs)

Do you mean `rio.write_crs`? `rio.set_crs` doesn't modify the xarray object.

**Comment by dcherian** [comment]
Yes I meant write_crs. I understanding the reasoning, so will close.
