### ISSUE TITLE
add explore function like in geopandas

### ISSUE THREAD

**Issue by 11904212** [corteva/rioxarray#794]
Geopandas provides a handy [explore function](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html) that creates an interactive folium-map and displays the GeoDataFrame on it. This function is particularly useful when working with Jupyter notebooks.

Since I frequently work with rioxarray and geopandas, I developed a custom xarray accessor to add this functionality to xarray DataArrays as well. Given that rioxarray is the powerhouse handling the heavy lifting, this seems like a good fit for a new feature.

While my implementation is somewhat basic (DataArrays only), it is works and can be combined with the GeoDataFrame. If you're interested, I can create a PR for this feature.

![Screenshot from 2024-07-03 17-52-06](https://github.com/corteva/rioxarray/assets/80150379/6da5b5bc-8c03-4782-9108-497c33c8ea1f)

**Comment by snowman2** [comment]
Thank you for your proposal. I think that would be a very useful feature. Plotting for rioxarray has been a topic of interest (see #208). My suggestion would be to create a separate library for plotting (e.g. `rioxarray-plot`). This will enable you to have the ability to quickly iterate on features, build a community around plotting with rioxarray, and choose whatever license you would like for your project.

**Comment by jessjaco** [comment]
FYI this functionality has been added to odc-geo: https://odc-geo.readthedocs.io/en/latest/_api/odc.geo.xr.ODCExtension.explore.html#odc.geo.xr.ODCExtension.explore

**Comment by 11904212** [comment]
> FYI this functionality has been added to odc-geo: https://odc-geo.readthedocs.io/en/latest/_api/odc.geo.xr.ODCExtension.explore.html#odc.geo.xr.ODCExtension.explore

looks good, I'll give it a try
