### ISSUE TITLE
2 reprojections causes a nodata border around result, changes resulting shape

### ISSUE THREAD

**Issue by rbavery** [corteva/rioxarray#82]
I'm working again with the NEON data, I have a file, `terrain`, in UTM that is initially the same size as another raster I would like to do raster math with later. I reproject to WGS84. When I then reproject this back to UTM, a nodata border is created. This behavior makes it difficult to to do raster math with xarrays and ideally the nodata border would be removed using something similar to this [solution](https://stackoverflow.com/questions/22032668/numpy-drop-rows-with-all-nan-or-0-values).
However I haven't been able to remove the nodata border since xarray doesn't support 2D boolean indexing. Is there was a better way to handle this in the reprojection stage?

The data can be accessed here: https://ndownloader.figshare.com/articles/2009586/versions/10

```python
import os
os.chdir("..")
import xarray
import rioxarray

surface = xarray.open_rasterio("data/NEON-DS-Airborne-Remote-Sensing/HARV/DSM/HARV_dsmCrop.tif")
terrain = xarray.open_rasterio("data/NEON-DS-Airborne-Remote-Sensing/HARV/DTM/HARV_dtmCrop.tif")

terrain.where(terrain != terrain.rio.nodata).plot()

surface.plot()

print(terrain.shape)
print(surface.shape)

from rasterio.crs import CRS

terrain_WGS84 = terrain.rio.reproject(dst_crs=CRS.from_epsg(4326))
print(terrain_WGS84.shape)
terrain_WGS84.plot()

terrain_WGS84_to_UTM = terrain_WGS84.rio.reproject(dst_crs=terrain.rio.crs)

terrain_WGS84_to_UTM.where(terrain_WGS84_to_UTM!=terrain_WGS84_to_UTM.rio.nodata).plot()

(terrain_WGS84_to_UTM.sel(band=1)==terrain_WGS84_to_UTM.rio.nodata).plot() 
```

The end result is attached
![02-bad-DTM-plot-01](https://user-images.githubusercontent.com/22258697/73117317-860c8380-3ef8-11ea-9cb0-bc1126c2a827.png)

Ideally, when reprojecting back, the nodata border would not exist. Maybe this should be handled by removing all rows and all columns that are all filled with nodata, but I haven't been able to accomplish this with xarray or numpy functions operating on DataArrays (to preserve metadata). I'm able to generate a mask of all rows or columns that have all of a nodata value, but not sure where to go from there or where it is best to incorporate this in the `reproject` function.

```
import numpy as np
partial_mask = np.all(terrain_WGS84_to_UTM.sel(band=1)==terrain_WGS84_to_UTM.rio.nodata, axis=1)
```

#### Output of ``rioxarray --version``
'0.0.18'

**Comment by snowman2** [comment]
I would recommend using `rioxarray.open_rasterio`. It has the `masked` and `mask_and_scale` kwargs that should address your issue.

See: https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray-open-rasterio

You can see it in action in the clip example in the docs.

**Comment by snowman2** [comment]
Also, I would recommend upgrading to version `0.0.19`.

**Comment by snowman2** [comment]
Ah, re-reading the issue I see what you are saying. The `drop=True` kwarg in `xarray.where` should do the trick.

`terrain_no_border= terrain_WGS84_to_UTM.where(terrain_WGS84_to_UTM!=terrain_WGS84_to_UTM.rio.nodata, drop=True)`

**Comment by rbavery** [comment]
Thanks for the tips. Using the `drop` keyword gets close to the expected result but the shape is still off because some rows have both true values and no data values and are therefore not removed by the drop keyword. I'd expect the result to be the same shape as the original, ` (band: 1, y: 1367, x: 1697)`

```
terrain_model_HARV_xarr_UTM18.where(terrain_model_HARV_xarr_UTM18!=terrain_model_HARV_xarr_UTM18.rio.nodata, drop=True)
```
```
<xarray.DataArray (band: 1, y: 1379, x: 1711)>
array([[[         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [         nan, 389.3999939 , 389.54998779, ...,          nan,
         345.13000488,          nan],
        [         nan, 389.3999939 , 389.44998169, ..., 344.97000122,
         345.13000488,          nan],
        ...,
        [         nan, 344.42999268, 344.47000122, ..., 309.25      ,
         309.29998779,          nan],
        [         nan, 344.41000366, 344.47000122, ...,          nan,
         309.3500061 ,          nan],
        [         nan,          nan,          nan, ...,          nan,
         309.3500061 ,          nan]]])
Coordinates:
  * x            (x) float64 7.315e+05 7.315e+05 ... 7.331e+05 7.332e+05
  * y            (y) float64 4.714e+06 4.714e+06 ... 4.712e+06 4.712e+06
  * band         (band) int64 1
    spatial_ref  int64 0
Attributes:
    transform:           (0.9928066390441307, 0.0, 731407.5575529601, 0.0, -0...
    scales:              (1.0,)
    offsets:             (0.0,)
    AREA_OR_POINT:       Area
    grid_mapping:        spatial_ref
    STATISTICS_MAXIMUM:  389.81997680664
    STATISTICS_MEAN:     344.8979433625
    STATISTICS_MINIMUM:  304.55999755859
    STATISTICS_STDDEV:   15.861471000978
    _FillValue:          -9999.0
```

I ran this with version `.19`

**Comment by rbavery** [comment]
I ran this process on QGIS and it looks like these artifacts might be unavoidable without adding extra arguments to the reproject function to control the output extent of the result, so I think it's probably best to just clip after the second reprojection.

**Comment by snowman2** [comment]
If you need the grid to be the same as it was originally, I think what you are looking for is `reproject_match`(https://corteva.github.io/rioxarray/stable/examples/reproject_match.html):

```python
import rioxarray
terrain = rioxarray.open_rasterio("data/NEON-DS-Airborne-Remote-Sensing/HARV/DTM/HARV_dtmCrop.tif")
terrain_WGS84 = terrain.rio.reproject("EPSG:4326")
terrain_WGS84_to_UTM = terrain_WGS84.rio.reproject_match(terrain)
```

**Comment by snowman2** [comment]
```python
terrain = rioxarray.open_rasterio(
    "NEON-DS-Airborne-Remote-Sensing/HARV/DTM/HARV_dtmCrop.tif",
    masked=True,
)
```
![image](https://user-images.githubusercontent.com/8699967/73601438-4c0a3580-4527-11ea-965a-1aeb2c4de03f.png)
```python
terrain_WGS84 = terrain.rio.reproject("EPSG:4326")
```
Notice how reprojecting the grid the first time introduces white space on the endges when reprojecting to WGS84:
![image](https://user-images.githubusercontent.com/8699967/73601444-5d534200-4527-11ea-864a-90792d85b526.png)

When using that same grid and allowing GDAL to auto-decide on the grid you want, you don't always get the effects you want as shown with the added nodata-border. I assume it is just propagating the grid expansion from the WGS84 grid due to the rotation.
![image](https://user-images.githubusercontent.com/8699967/73601463-cc309b00-4527-11ea-9f79-1033037e4555.png)

But, if you want it to match the original grid, it will happily do that for you:
```python
terrain_WGS84_to_UTM = terrain_WGS84.rio.reproject_match(terrain)
```
![image](https://user-images.githubusercontent.com/8699967/73601465-ed918700-4527-11ea-9dbc-8ec39a7bad57.png)

**Comment by rbavery** [comment]
Thanks a bunch for the help @snowman2 I'll go with `reproject_match`, I found that `clip_box` doesn't actually result in arrays of the same shape probably due to how border pixels are handled (I assume I'm misusing that func and that reproject_match is the way to go).
