### ISSUE TITLE
Different scales/offsets warning

### ISSUE THREAD

**Issue by dzanaga** [corteva/rioxarray#833]
While opening a geotiff with different scales I got this warning:
https://github.com/corteva/rioxarray/blob/master/rioxarray/_io.py#L673
```
    if len(set(riods.scales)) > 1:
        attrs["scales"] = riods.scales
        warnings.warn(
            "Offsets differ across bands. The 'scale_factor' attribute will "
            "not be added. See the 'scales' attribute."
        )
```
It was a bit confusing as the offsets were all 0s. Might be clearer if the warning would be "Scales differ across bands..."

**Comment by snowman2** [comment]
Thanks for bringing that up. A PR is welcome.
