### ISSUE TITLE
Appveyor build failing again

### ISSUE THREAD

**Issue by snowman2** [corteva/rioxarray#84]
https://ci.appveyor.com/project/snowman2/rioxarray/builds/30418759
```
pytest --cov-report term-missing --cov=rioxarray
ImportError while loading conftest 'C:\projects\rioxarray\test\conftest.py'.
test\conftest.py:5: in <module>
    from rioxarray.rioxarray import UNWANTED_RIO_ATTRS
rioxarray\__init__.py:8: in <module>
    import rioxarray.rioxarray  # noqa
rioxarray\rioxarray.py:18: in <module>
    import rasterio.warp
c:\miniconda3-x64\envs\test\lib\site-packages\rasterio\__init__.py:22: in <module>
    from rasterio._base import gdal_version
E   ImportError: DLL load failed: The specified module could not be found.

```

**Comment by Zeitsperre** [comment]
I've seen a similar problem trying to install the basic GIS libraries in the Windows image on Travis CI. Is it possible that the rasterio package is being built against an incompatible GDAL?

**Comment by snowman2** [comment]
It says `libgdal-2.4.4` for the GDAL version. So, it should be fine. I also see the warning about using `python -m pip` that I am going to investigate.

**Comment by snowman2** [comment]
Possibly related: https://github.com/conda-forge/rasterio-feedstock/issues/149

**Comment by snowman2** [comment]
#85 seems to haven fixed it
