### ISSUE TITLE
Export raster after reproject, not working.

### ISSUE THREAD

**Issue by danhamill** [corteva/rioxarray#96]
I have a question that I am not able to figure out using previous issues and other stackoverflow posts. My question is similar to #47, but I could not make work with my dataset. I am attempting to reproject and export images in a geotiff format.

If I have an xarray dataset `d`.  For reproducibility, here I have uploaded [`d`](https://github.com/corteva/rioxarray/files/4344002/test.zip) as a zip archive to this issue.

```
import os
os.environ['GDAL_DATA'] = r"C:\Program Files\GDAL\gdal-data"
import xarray as xr
import rioxarray
import pandas as pd

data = xr.open_dataset('test.nc')

d = data.SWE

d.rio.set_spatial_dims('lon','lat', inplace=True)
d.rio.set_crs("epsg:4326")
d.rio.reproject('+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs')

oName = rf"C:\workspace\ririe\test\{pd.to_datetime(d.time.values).strftime('%Y-%m-%d')}.tif"

d.rio.to_raster(oName)
```

This outputs a raster but is projected in the original epsg:4326 projection.  How can I fix this?

```
# Name                    Version                   Build  Channel
rioxarray                 0.0.23                   pypi_0    pypi
xarray                    0.15.0                   pypi_0    pypi
```

**Comment by djhoese** [comment]
Reproject should be returning a *new* dataset: https://corteva.github.io/rioxarray/stable/examples/reproject.html#Reproject. You'll need to assign the result to a new variable name and use that from then on.

**Comment by snowman2** [comment]
@danhamill, what @djhoese said is correct.

Just need to update the bottom section of your code:
```python
reprojected = d.rio.reproject('+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs')
oName = rf"C:\workspace\ririe\test\{pd.to_datetime(d.time.values).strftime('%Y-%m-%d')}.tif"
reprojected.rio.to_raster(oName)
```

**Comment by danhamill** [comment]
Simple enough!  Thanks for the quick reply and great package.
